import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';
import zlib from 'node:zlib';
import { fileURLToPath } from 'node:url';

const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const html=fs.readFileSync(path.join(root,'index.html'),'utf8');
const script=html.match(/<script>([\s\S]*?)<\/script>/)?.[1];
assert(script,'index.html must contain a game script');

for(const match of html.matchAll(/loadSprite\('([^']+)'/g))assert(fs.existsSync(path.join(root,match[1])),`missing sprite: ${match[1]}`);
assert(fs.existsSync(path.join(root,'Background OST.mp3')),'missing background OST');

const paeth=(a,b,c)=>{const p=a+b-c,pa=Math.abs(p-a),pb=Math.abs(p-b),pc=Math.abs(p-c);return pa<=pb&&pa<=pc?a:pb<=pc?b:c;};
function pngAlphaStats(png,columns=3,rows=2){
  const width=png.readUInt32BE(16),height=png.readUInt32BE(20);assert.equal(png[24],8,'VFX PNG must use 8-bit channels');assert.equal(png[25],6,'VFX PNG must use RGBA color');assert.equal(png[28],0,'VFX PNG must be non-interlaced');
  const chunks=[];for(let offset=8;offset+12<=png.length;){const length=png.readUInt32BE(offset),type=png.toString('ascii',offset+4,offset+8);if(type==='IDAT')chunks.push(png.subarray(offset+8,offset+8+length));offset+=length+12;if(type==='IEND')break;}
  const packed=zlib.inflateSync(Buffer.concat(chunks)),stride=width*4,previous=Buffer.alloc(stride),row=Buffer.alloc(stride),cells=Array.from({length:columns*rows},()=>({transparent:0,visible:0}));assert.equal(packed.length,height*(stride+1),'unexpected VFX PNG scanline size');let cursor=0,transparent=0,visible=0;
  for(let y=0;y<height;y++){const filter=packed[cursor++];assert(filter>=0&&filter<=4,'unsupported PNG filter');for(let x=0;x<stride;x++){const raw=packed[cursor++],left=x>=4?row[x-4]:0,up=previous[x],upperLeft=x>=4?previous[x-4]:0,predictor=filter===0?0:filter===1?left:filter===2?up:filter===3?Math.floor((left+up)/2):paeth(left,up,upperLeft);row[x]=(raw+predictor)&255;}for(let x=3;x<stride;x+=4){const frame=Math.min(cells.length-1,Math.floor(((x-3)/4)/(width/columns))+columns*Math.floor(y/(height/rows)));if(row[x]===0){transparent++;cells[frame].transparent++;}else{visible++;cells[frame].visible++;}}previous.set(row);}
  return{width,height,transparent,visible,cells};
}

class MockElement {
  constructor(id=''){this.id=id;this.value='0';this.textContent='';this.inert=false;this.attributes=new Map();this.classList={toggle(){},add(){},remove(){}};}
  addEventListener(){} setAttribute(k,v){this.attributes.set(k,String(v));} closest(){return null;} contains(){return false;} focus(){} requestFullscreen(){document.fullscreenElement=this;}
}

let saveCalls=0,contextDepth=0,drawImageCalls=[];
const gradient={addColorStop(){}};
const context2d=new Proxy({
  setTransform(){},createLinearGradient(){return gradient;},save(){saveCalls++;contextDepth++;},restore(){contextDepth--;if(contextDepth<0)throw new Error('canvas restore without save');},drawImage(...args){drawImageCalls.push(args);},measureText(){return{width:0}}
},{get(target,key){if(key in target)return target[key];return()=>{};},set(target,key,value){target[key]=value;return true;}});
const elements=new Map();
const canvas=new MockElement('game');canvas.width=0;canvas.height=0;canvas.style={};canvas.getContext=()=>context2d;canvas.getBoundingClientRect=()=>({left:0,top:0});
elements.set('game',canvas);
const element=id=>{if(!elements.has(id))elements.set(id,new MockElement(id));return elements.get(id);};

const storage=new Map();
const document={
  activeElement:null,hidden:false,fullscreenElement:null,documentElement:new MockElement('documentElement'),
  getElementById:element,addEventListener(){},exitFullscreen(){this.fullscreenElement=null;}
};
const localStorage={getItem:key=>storage.get(key)??null,setItem:(key,value)=>storage.set(key,String(value))};
class MockImage {constructor(){this.complete=false;this.naturalWidth=0;this.naturalHeight=0;this.listeners=new Map();this._src='';}addEventListener(type,fn){this.listeners.set(type,fn);}set src(value){this._src=value;}get src(){return this._src;}}
class MockAudio {constructor(src){this.src=src;this.loop=false;this.preload='';this.volume=1;this.muted=false;this.paused=true;}play(){this.paused=false;return Promise.resolve();}pause(){this.paused=true;}}
class MockAudioContext {
  constructor(){this.currentTime=0;this.state='running';this.destination={};}
  resume(){this.state='running';return Promise.resolve();}
  createGain(){return{gain:{value:1,setValueAtTime(){},exponentialRampToValueAtTime(){}},connect(){return this;},disconnect(){}};}
  createOscillator(){return{type:'sine',frequency:{setValueAtTime(){},exponentialRampToValueAtTime(){}},connect(){return this;},disconnect(){},start(){},stop(){},addEventListener(){}};}
}

const sandbox={
  console,Math,JSON,Number,Boolean,Set,Map,Object,Array,String,Date,Error,Promise,
  innerWidth:1280,innerHeight:720,devicePixelRatio:1,performance:{now:()=>1000},
  document,localStorage,Image:MockImage,Audio:MockAudio,AudioContext:MockAudioContext,webkitAudioContext:MockAudioContext,
  Element:MockElement,addEventListener(){},requestAnimationFrame(){},setTimeout,clearTimeout
};
sandbox.window=sandbox; sandbox.globalThis=sandbox;
vm.createContext(sandbox);
vm.runInContext(`${script}\n;globalThis.__test={CFG,STAGE2,SPRITES,AudioFX,PrismWarden,Player,GroundEnemy,Stage2Hero,CrystalStalker,SporeDrone,AstralDevourer,rayRect,game};`,sandbox,{filename:'index.html'});

const {CFG,STAGE2,SPRITES,AudioFX,PrismWarden,Player,GroundEnemy,Stage2Hero,CrystalStalker,SporeDrone,AstralDevourer,rayRect,game}=sandbox.__test;
const markSpriteLoaded=image=>Object.assign(image,{complete:true,naturalWidth:1536,naturalHeight:1024,width:1536,height:1024});
game.audio.muted=true;

assert.equal(CFG.ultimateMaxCharges,3);
assert.equal(CFG.ultimateRadius,440);
for(const [asset,columns] of [['astra-walk-frames-v3.png',4],['astra-sprint-frames-v1.png',4]]){const alpha=pngAlphaStats(fs.readFileSync(path.join(root,'assets','sprites',asset)),columns,2),pixels=alpha.width*alpha.height;assert(alpha.transparent>pixels*.2&&alpha.visible>pixels*.2,`${asset} must have a true transparent background`);for(const [frame,cell] of alpha.cells.entries())assert(cell.transparent>1000&&cell.visible>1000,`${asset} frame ${frame} must contain transparent space and character art`);}
const idleAlpha=pngAlphaStats(fs.readFileSync(path.join(root,'assets','sprites','astra-idle-cape-frames-v4.png')),2,2),idlePixels=idleAlpha.width*idleAlpha.height;assert(idleAlpha.transparent>idlePixels*.2&&idleAlpha.visible>idlePixels*.2,'cape-only idle sheet must have a true transparent background');for(const [frame,cell] of idleAlpha.cells.entries())assert(cell.transparent>1000&&cell.visible>1000,`cape-only idle frame ${frame} must contain transparent space and character art`);

game.mode='classic';game.started=true;game.reset();game.audio.muted=true;
assert.equal(game.player.launchDuration,.6,'power-launch charge must last 0.60 seconds');
game.player.onGround=true;game.player.vx=CFG.runMax;game.player.updateLocomotion(.12);assert(game.player.groundMotion>.7,'Astra must smoothly enter the upgraded walk cycle');markSpriteLoaded(SPRITES.astraWalk);markSpriteLoaded(SPRITES.astraSprint);drawImageCalls=[];game.player.draw(context2d,game);assert(drawImageCalls.some(args=>args[0]===SPRITES.astraWalk),'Astra walking must use the dedicated eight-frame walk sheet');game.player.boosting=true;game.player.updateLocomotion(.12);assert(game.player.sprintMotion>.7,'Astra must smoothly enter the upgraded sprint cycle');drawImageCalls=[];game.player.draw(context2d,game);assert(drawImageCalls.some(args=>args[0]===SPRITES.astraSprint),'Astra sprinting must use the dedicated eight-frame sprint sheet without frame blending');game.player.onGround=false;game.player.boosting=false;game.player.updateLocomotion(.25);assert(game.player.groundMotion<.1&&game.player.sprintMotion<.1,'Astra locomotion must smoothly settle when leaving the ground');game.player.vx=0;
game.reset();game.player.onGround=true;game.input.keys.add('shift');game.input.keys.add('w');game.player.update(.016,game);assert(game.player.launchCharging,'Shift + W must begin a grounded power-launch charge');assert.equal(game.player.vx,0,'power-launch charge must lock horizontal movement');game.player.draw(context2d,game);assert.equal(contextDepth,0,'power-launch charge drawing must balance canvas state');game.input.keys.delete('w');game.player.update(.016,game);assert.equal(game.player.launchCharging,false,'releasing the combo during charge must cancel cleanly');assert.equal(game.player.flying,false,'cancelled power launch must not toggle flight');game.input.clear();game.reset();game.player.onGround=true;game.input.keys.add('shift');game.input.keys.add('w');for(let i=0;i<30;i++)game.player.update(1/30,game);assert.equal(game.player.flying,true,'completed power launch must enable flight');assert.equal(game.player.speedBuild,1,'power launch must start at maximum boost build');assert(Math.hypot(game.player.vx,game.player.vy)>CFG.speedFlyMax*.95,'power launch must use maximum boosted flight speed');assert(game.launchWaves.length===1,'power launch must create one takeoff shockwave');game.player.draw(context2d,game);assert.equal(contextDepth,0,'power-launch burst drawing must balance canvas state');game.input.clear();
assert.equal(game.player.vx,0,'completed power launch must travel perfectly straight upward');
assert.equal(game.player.vy,-CFG.speedFlyMax,'completed power launch must use maximum boosted flight speed vertically');
game.reset();game.player.onGround=true;game.input.keys.add('d');game.player.update(.08,game);assert(game.player.x>game.player.spawnX,'normal grounded movement must remain available after power-launch integration');game.input.clear();
const wardenVfxPng=fs.readFileSync(path.join(root,'assets','sprites','prism-warden-vfx-frames-v1.png')),wardenAlpha=pngAlphaStats(wardenVfxPng),wardenPixels=wardenAlpha.width*wardenAlpha.height;assert.equal(wardenAlpha.width,1536);assert.equal(wardenAlpha.height,1024);assert(wardenAlpha.transparent>wardenPixels*.2&&wardenAlpha.visible>wardenPixels*.2,'Prism Warden VFX must contain genuine transparent and visible pixels');for(const [frame,cell] of wardenAlpha.cells.entries())assert(cell.transparent>1000&&cell.visible>1000,`Prism Warden VFX frame ${frame} must contain transparency and artwork`);assert.equal(game.wardenEffects.length,0,'classic mode must reset Warden effects');
game.input.keys.add(' ');game.input.pressed.add(' ');
game.player.updateBeamCharge(.4,game);
game.input.pressed.clear();game.input.keys.delete(' ');game.input.released.add(' ');
game.player.updateBeamCharge(.016,game);
assert.equal(game.player.chargingBeam,false,'releasing Space must end beam charging');
assert.equal(game.beams.length,1,'releasing a charged Space must fire one super beam');
const classicSuperBeam=game.beams[0];assert(Math.hypot(classicSuperBeam.ex-classicSuperBeam.x,classicSuperBeam.ey-classicSuperBeam.y)>=CFG.superBeamRange*.99,'Stage One Super Beam must span the full screen and world direction');assert.equal(classicSuperBeam.life,classicSuperBeam.max,'Super Beam must begin at full visual intensity');

game.reset();const classicTarget=game.enemies[0],classicSecondTarget=game.enemies[1],classicOrigin=game.player.beamOrigin(),classicTargetHp=classicTarget.hp,classicSecondTargetHp=classicSecondTarget.hp;classicTarget.x=classicOrigin.x+280;classicTarget.y=classicOrigin.y-classicTarget.h/2;classicSecondTarget.x=classicOrigin.x+610;classicSecondTarget.y=classicOrigin.y-classicSecondTarget.h/2;game.input.mouse.x=classicTarget.x+classicTarget.w/2-game.camera.x;game.input.mouse.y=classicTarget.y+classicTarget.h/2-game.camera.y;game.input.mouse.down=true;game.player.update(.016,game);assert(game.heatVision,'Stage One must use Astra’s continuous heat vision');assert.equal(game.beams.length,0,'held heat vision must not create Stage One projectile shots');assert(Math.hypot(game.heatVision.ex-game.heatVision.x,game.heatVision.ey-game.heatVision.y)>=CFG.heatVisionRange*.99,'Stage One heat vision must reach beyond the visible map');assert(classicTarget.hp<classicTargetHp&&classicSecondTarget.hp<classicSecondTargetHp,'Stage One heat vision must pierce every target in its path');game.input.mouse.down=false;game.player.update(.016,game);assert.equal(game.heatVision,null,'releasing the primary beam must clear Stage One heat vision');game.input.clear();
const visibleTrooper=game.enemies[0],upperBodyBeamY=visibleTrooper.y-12;assert.equal(rayRect(0,upperBodyBeamY,1,0,visibleTrooper,CFG.heatVisionRange),null,'the old compact trooper physics box must not mask this regression');assert.notEqual(rayRect(0,upperBodyBeamY,1,0,visibleTrooper.beamHitbox(),CFG.heatVisionRange),null,'the rendered trooper torso must be hittable by a beam');
game.reset();const beamTrooper=game.enemies[0],beamOrigin=game.player.beamOrigin(),beamTrooperHp=beamTrooper.hp;beamTrooper.x=beamOrigin.x+320;beamTrooper.y=beamOrigin.y+18;game.input.mouse.x=beamTrooper.x+beamTrooper.w/2-game.camera.x;game.input.mouse.y=beamOrigin.y-game.camera.y;game.input.mouse.down=true;game.player.update(.016,game);assert(beamTrooper.hp<beamTrooperHp,'continuous heat vision must damage a visible trooper upper body outside its movement box');game.input.mouse.down=false;game.input.clear();

game.startBossIntro();const boss=game.boss,wardenIntroEffect=game.wardenEffects.find(effect=>effect.frame===5&&effect.layer==='behind');assert(boss instanceof PrismWarden);assert(wardenIntroEffect,'Warden intro must create its generated phase halo');assert(wardenIntroEffect.life>=game.encounterTimer,'Warden intro halo must cover the full entrance');const wardenBossX=boss.x;boss.x+=24;wardenIntroEffect.update(0,game);assert.equal(wardenIntroEffect.x,boss.cx,'Warden intro halo must follow the moving boss');boss.x=wardenBossX;wardenIntroEffect.update(0,game);markSpriteLoaded(SPRITES.wardenVfx);drawImageCalls=[];wardenIntroEffect.draw(context2d);assert(drawImageCalls.some(args=>args[0]===SPRITES.wardenVfx&&args[1]===1024&&args[2]===512),'loaded Warden halo must draw generated frame 5');assert.equal(contextDepth,0,'Warden halo drawing must balance canvas state');game.encounterState='boss-fight';boss.phase=2;boss.hp=1000;boss.attackSerial=0;boss.facing=1;game.player.x=4720;
const wardenProjectileCount=game.projectiles.length,wardenEffectCount=game.wardenEffects.length;boss.fireVolley(game);assert(game.projectiles.length>wardenProjectileCount,'Warden volley must create projectiles');assert(game.projectiles[wardenProjectileCount].x>boss.cx,'Warden bolts must originate from its visible cannon');assert(game.wardenEffects.length>wardenEffectCount&&game.wardenEffects.at(-1).frame===0,'Warden volley must create its generated muzzle effect');drawImageCalls=[];game.projectiles.at(-1).draw(context2d);assert(drawImageCalls.some(args=>args[0]===SPRITES.wardenVfx&&args[1]===0&&args[2]===0),'loaded Warden bolt must draw generated frame 0');assert.equal(contextDepth,0,'Warden projectile drawing must balance canvas state');boss.setState('ranged',0);boss.update(.016,game);assert.equal(boss.state,'ranged-fire','Warden must hold its cannon firing frame when the volley launches');assert.equal(boss.animationFrame().frame,4,'Warden firing state must use the muzzle-flash frame');boss.stateTimer=0;boss.update(.016,game);assert.equal(boss.state,'recover');
boss.chooseAttack(game);assert.equal(boss.state,'slam-windup');assert(boss.slamLiftY<=boss.slamTargetY,'slam windup must remain above its landing point');
boss.stateTimer=0;boss.update(.016,game);assert.equal(boss.state,'slam-drop');assert(boss.slamTargetY>=boss.slamStartY,'slam drop must never interpolate upward');boss.stateTimer=0;boss.update(.016,game);assert.equal(boss.state,'slam-impact');assert(game.wardenEffects.at(-1).frame===3,'Warden slam must create its generated crystal impact');drawImageCalls=[];game.shockwaves[0].draw(context2d);assert(drawImageCalls.some(args=>args[0]===SPRITES.wardenVfx&&args[1]===512&&args[2]===512),'loaded Warden shockwave must draw generated frame 4');assert.equal(contextDepth,0,'Warden shockwave drawing must balance canvas state');
boss.x=4300;boss.y=700;boss.vx=0;boss.vy=0;boss.vfxTimer=.04;boss.setState('dash-windup',0);game.player.x=4800;boss.update(.016,game);assert.equal(boss.state,'dash');assert.equal(boss.vfxTimer,0,'each Warden dash must reset its trail timer');boss.update(.016,game);assert(game.wardenEffects.some(effect=>effect.frame===2),'Warden dash must create generated afterimages immediately');for(let i=0;i<50;i++)game.spawnWardenEffect(2,boss.cx,boss.cy,100,.3);assert(game.wardenEffects.length<=40,'Warden VFX must stay capped during effect-heavy combat');const expiringWardenEffect=game.wardenEffects.at(-1);expiringWardenEffect.life=.001;game.update(.016);assert(!game.wardenEffects.includes(expiringWardenEffect),'expired Warden VFX must be removed');

game.projectiles.push({});game.shockwaves.push({});boss.kill(game);
assert.equal(game.projectiles.length,0,'boss death must clear projectiles');
assert.equal(game.shockwaves.length,0,'boss death must clear shockwaves');
assert.equal(game.wardenEffects.length,1,'Warden death must replace active effects with its finishing halo');assert.equal(game.wardenEffects[0].frame,5,'Warden death must use the generated phase halo');

game.reset();const fallen=new GroundEnemy(100,CFG.worldH+100);fallen.update(.016,game);assert.equal(fallen.dead,true,'fallen enemies must not block stage progression');

game.mode='god';game.reset();game.player.y=CFG.worldH+100;game.player.update(.016,game);
assert.equal(game.player.y,game.player.spawnY,'God Mode must recover from the void');
game.player.flying=true;game.player.y=-80;game.player.vy=-300;game.player.update(.016,game);
assert.equal(game.player.y,20,'player must remain inside the top world boundary');

game.player.dead=true;game.player.invuln=1;game.player.deathAt=sandbox.performance.now();saveCalls=0;game.player.draw(context2d,game);
assert(saveCalls>0,'death animation must render even while invulnerability is active');

game.mode='classic';game.reset();game.started=true;game.player.dead=true;game.input.pressed.add('escape');game.update(.016);
assert.equal(game.paused,true,'Escape must open the menu after death');
game.input.keys.add('shift');game.projectiles.push({});game.restart();
assert.equal(game.input.keys.size,0,'restart must clear held input');assert.equal(game.projectiles.length,0,'restart must clear active attacks');assert.equal(game.player.dead,false);

game.particles.length=0;game.burst(0,0,'#fff',Number.MAX_SAFE_INTEGER,100);assert.equal(game.particles.length,520,'particle count must be capped');

game.audio.setMusicVolume(.23);game.audio.setSfxVolume(.41);game.audio.setMuted(true);
const restoredAudio=new AudioFX();assert.equal(restoredAudio.musicVolume,.23);assert.equal(restoredAudio.sfxVolume,.41);assert.equal(restoredAudio.muted,true);

game.mode='stage2';game.started=true;game.audio.muted=true;game.resetStage2();
assert.equal(STAGE2.worldW,6400);assert.equal(game.stage2Platforms.length,13);assert.equal(game.stage2Enemies.length,10);assert(game.stage2Hero instanceof Stage2Hero);assert(game.stage2Hero instanceof Player,'Stage Two must use the same Astra character system');assert.equal(game.stage2Hero.w,CFG.playerW);assert.equal(game.stage2Hero.ultimateCharges,CFG.ultimateMaxCharges);assert(game.stage2Enemies.some(enemy=>enemy instanceof CrystalStalker));assert(game.stage2Enemies.some(enemy=>enemy instanceof SporeDrone));
game.stage2Hero.onGround=true;game.input.keys.add('shift');game.input.keys.add('w');for(let i=0;i<30;i++)game.stage2Hero.update(1/30,game);assert.equal(game.stage2Hero.flying,true,'Stage Two must use the same power-launch flight burst');assert.equal(game.stage2Hero.speedBuild,1,'Stage Two power launch must start at maximum boost build');assert(game.stage2LaunchWaves.length===1,'Stage Two power launch must create a takeoff shockwave');game.input.clear();game.resetStage2();
game.input.mouse.x=game.w;game.input.mouse.y=game.h*.5;game.stage2Hero.fireSuperBeam(game,1);assert.equal(game.stage2Beams.length,1,'Stage Two must inherit the shared Super Beam');const stage2SuperBeam=game.stage2Beams[0];assert(Math.hypot(stage2SuperBeam.ex-stage2SuperBeam.x,stage2SuperBeam.ey-stage2SuperBeam.y)>=CFG.superBeamRange*.99,'Stage Two Super Beam must span the full screen and world direction');game.resetStage2();
game.stage2Hero.onGround=true;game.stage2Hero.vx=CFG.runMax;game.stage2Hero.boosting=true;game.stage2Hero.updateLocomotion(.12);assert(game.stage2Hero.groundMotion>.7&&game.stage2Hero.sprintMotion>.7,'Stage Two must inherit Astra’s upgraded locomotion system');game.stage2Hero.vx=0;game.stage2Hero.boosting=false;
game.stage2Hero.onGround=true;const stage2StartX=game.stage2Hero.x;game.input.keys.add('d');game.stage2Hero.update(.08,game);assert(game.stage2Hero.x>stage2StartX,'Stage Two normal grounded movement must remain available after power-launch integration');game.input.clear();
assert(game.stage2Platforms.some(platform=>platform.x<=game.stage2ArenaLeft&&platform.x+platform.w>=STAGE2.worldW&&platform.y===1450),'boss arena must have one continuous floor');
for(const facade of game.stage2Platforms.filter(platform=>platform.facade))assert(game.stage2Platforms.some(base=>!base.facade&&base.y===facade.y+facade.h&&base.x<=facade.x&&base.x+base.w>=facade.x+facade.w),`facade at ${facade.x} must be fully supported by its floor`);
for(const asset of ['stage2-crystal-stalker-frames-v1.png','stage2-spore-drone-frames-v1.png','stage2-astral-devourer-frames-v2.png','stage2-boss-vfx-frames-v1.png']){const png=fs.readFileSync(path.join(root,'assets','sprites',asset));assert.equal(png[25],6,`${asset} must retain PNG alpha transparency`);if(asset==='stage2-boss-vfx-frames-v1.png'){const alpha=pngAlphaStats(png),pixels=alpha.width*alpha.height;assert.equal(alpha.width,1536);assert.equal(alpha.height,1024);assert(alpha.transparent>pixels*.2&&alpha.visible>pixels*.2,'Stage 2 boss VFX must contain genuine transparent and visible pixels');for(const [frame,cell] of alpha.cells.entries())assert(cell.transparent>1000&&cell.visible>1000,`Stage 2 boss VFX frame ${frame} must contain transparency and artwork`);}}
const openingEnemy=game.stage2Enemies[0],openingAnim=openingEnemy.anim,openingX=openingEnemy.x,openingHp=game.stage2Hero.hp;for(let i=0;i<60;i++)game.update(1/60);assert(openingEnemy.anim>openingAnim&&openingEnemy.x>openingX+20,'Stage Two enemies must patrol and animate during the opening card');assert.equal(game.stage2Hero.hp,openingHp,'opening patrol movement must not damage Astra before combat aggro begins');
const facadeWalker=new CrystalStalker(830,1382);facadeWalker.attackCd=99;facadeWalker.moveDir=1;facadeWalker.vx=120;game.stage2Hero.x=1160;game.stage2Hero.y=1384;for(let i=0;i<120;i++)facadeWalker.update(1/60,game);assert(facadeWalker.x>930,'ground stalkers must cross decorative facades instead of getting pinned against them');
const edgeWalker=new CrystalStalker(1250,1382);edgeWalker.attackCd=99;edgeWalker.moveDir=1;edgeWalker.vx=120;game.stage2Hero.x=3000;for(let i=0;i<90;i++)edgeWalker.update(1/60,game);assert(edgeWalker.x<1230&&edgeWalker.moveDir<0,'stalkers must commit to a ledge turn instead of oscillating in place');game.stage2Hero.x=120;game.stage2Hero.y=1450-CFG.playerH;
const stage2Target=game.stage2Enemies[0],stage2SecondTarget=game.stage2Enemies[1],stage2Origin=game.stage2Hero.beamOrigin(),stage2TargetHp=stage2Target.hp,stage2SecondTargetHp=stage2SecondTarget.hp;stage2Target.x=stage2Origin.x+280;stage2Target.y=stage2Origin.y-stage2Target.h/2;stage2SecondTarget.x=stage2Origin.x+610;stage2SecondTarget.y=stage2Origin.y-stage2SecondTarget.h/2;game.input.mouse.x=stage2Target.x+stage2Target.w/2-game.camera.x;game.input.mouse.y=stage2Target.y+stage2Target.h/2-game.camera.y;game.input.mouse.down=true;game.stage2Hero.update(.016,game);assert(game.stage2HeatVision,'holding the primary beam must create continuous heat vision');assert.equal(game.stage2Beams.length,0,'held heat vision must not create repeated projectile shots');assert(Math.hypot(game.stage2HeatVision.ex-game.stage2HeatVision.x,game.stage2HeatVision.ey-game.stage2HeatVision.y)>=STAGE2.heatVisionRange*.99,'heat vision must extend past the visible map');assert(stage2Target.hp<stage2TargetHp,'continuous heat vision must damage its first target');assert(stage2SecondTarget.hp<stage2SecondTargetHp,'heat vision must pierce targets instead of stopping at the first one');game.input.mouse.down=false;game.input.clear();
const stage2Charges=game.stage2Hero.ultimateCharges;game.stage2Hero.castUltimate(game);assert.equal(game.stage2Hero.ultimateCharges,stage2Charges-1,'Stage Two must retain Prism Nova');assert(game.stage2Waves.length>0);
game.draw();game.update(.016);assert.equal(game.stage2Encounter,'clear-hostiles');
game.stage2Enemies.length=0;game.stage2Hero.x=5200;game.update(.016);const stage2IntroEffect=game.stage2BossEffects.find(effect=>effect.frame===5&&effect.layer==='behind');assert.equal(game.stage2Encounter,'boss-intro');assert(game.stage2Boss instanceof AstralDevourer);assert(stage2IntroEffect,'boss intro must create its generated phase-halo effect');assert(stage2IntroEffect.life>=game.stage2Timer,'Stage 2 intro halo must cover the full entrance');const stage2IntroBossX=game.stage2Boss.x;game.stage2Boss.x+=30;stage2IntroEffect.update(0,game);assert.equal(stage2IntroEffect.x,game.stage2Boss.cx,'Stage 2 intro halo must follow the moving boss');game.stage2Boss.x=stage2IntroBossX;stage2IntroEffect.update(0,game);markSpriteLoaded(SPRITES.stage2BossVfx);drawImageCalls=[];stage2IntroEffect.draw(context2d);assert(drawImageCalls.some(args=>args[0]===SPRITES.stage2BossVfx&&args[1]===1024&&args[2]===512),'loaded Stage 2 halo must draw generated frame 5');assert.equal(contextDepth,0,'Stage 2 halo drawing must balance canvas state');
game.stage2Timer=0;game.update(.016);assert.equal(game.stage2Encounter,'boss-fight');game.stage2Boss.hit(100,game);assert(game.stage2Boss.hp<game.stage2Boss.maxHp);
game.stage2Boss.x=5700;game.stage2Hero.x=5200;const bossBoltCount=game.stage2Projectiles.length,bossEffectCount=game.stage2BossEffects.length;game.stage2Boss.fireBolts(game);const leftBolts=game.stage2Projectiles.slice(bossBoltCount);assert(leftBolts.length&&leftBolts.every(projectile=>projectile.kind==='boss-bolt'),'boss bolts must use generated VFX projectiles');assert(leftBolts[0].x<game.stage2Boss.cx,'left-facing boss bolts must originate from the visible left cannon');assert(game.stage2BossEffects.length>bossEffectCount&&game.stage2BossEffects.at(-1).frame===0,'boss volley must create a generated muzzle effect');drawImageCalls=[];leftBolts[0].draw(context2d);assert(drawImageCalls.some(args=>args[0]===SPRITES.stage2BossVfx&&args[1]===0&&args[2]===0),'loaded Stage 2 bolt must draw generated frame 0');assert.equal(contextDepth,0,'Stage 2 projectile drawing must balance canvas state');game.stage2Hero.x=6100;const rightBoltCount=game.stage2Projectiles.length;game.stage2Boss.fireBolts(game);assert(game.stage2Projectiles[rightBoltCount].x>game.stage2Boss.cx,'right-facing boss bolts must originate from the visible right cannon');game.stage2Hero.x=5350;
const bossPulseCount=game.stage2Projectiles.length;game.stage2Boss.firePulse(game);assert(game.stage2Projectiles.length>bossPulseCount&&game.stage2Projectiles.slice(bossPulseCount).every(projectile=>projectile.kind==='boss-pulse'),'boss pulse must use generated radial projectiles');assert(game.stage2BossEffects.at(-1).frame===1&&game.stage2BossEffects.at(-1).layer==='behind','boss pulse must create its generated radial sigil');
game.stage2Boss.phase=1;game.stage2Boss.hp=game.stage2Boss.maxHp*.5;game.stage2Boss.vx=240;game.stage2Boss.vy=0;game.stage2Boss.setState('recover',1);game.stage2Boss.update(.016,game);const stage2PhaseEffect=game.stage2BossEffects.at(-1);assert(stage2PhaseEffect.frame===5&&stage2PhaseEffect.followBoss,'Stage 2 phase halo must follow the drifting boss');game.stage2Boss.x+=28;stage2PhaseEffect.update(0,game);assert.equal(stage2PhaseEffect.x,game.stage2Boss.cx,'Stage 2 phase halo must stay centered on the boss');
game.stage2Hero.x=game.stage2ArenaLeft-100;game.update(.016);assert(game.stage2Hero.x>=game.stage2ArenaLeft+18,'boss barrier must lock behind Astra');
game.stage2Boss.x=5600;game.stage2Boss.y=500;game.stage2Boss.vx=300;game.stage2Boss.vy=0;game.stage2Boss.setState('bolts-windup',1);const bossCoastX=game.stage2Boss.x;game.stage2Boss.update(.1,game);assert(game.stage2Boss.x>bossCoastX&&game.stage2Boss.vx<300,'boss windups must decelerate smoothly instead of freezing in place');game.stage2Boss.setState('bolts-windup',0);game.stage2Boss.update(.016,game);assert.equal(game.stage2Boss.state,'bolts-fire','Stage 2 boss must hold its casting pose when bolts launch');game.stage2Boss.stateTimer=0;game.stage2Boss.update(.016,game);assert.equal(game.stage2Boss.state,'recover');game.stage2Boss.setState('pulse-windup',0);game.stage2Boss.update(.016,game);assert.equal(game.stage2Boss.state,'pulse-fire','Stage 2 boss must hold its casting pose when the radial pulse launches');game.stage2Boss.stateTimer=0;game.stage2Boss.update(.016,game);assert.equal(game.stage2Boss.state,'recover');
game.stage2Boss.slamX=5500;game.stage2Boss.setState('slam-windup',0);game.stage2Boss.update(.016,game);assert.equal(game.stage2Boss.state,'slam-drop');game.stage2Boss.y=game.stage2Boss.arenaFloor-game.stage2Boss.h+2;game.stage2Boss.vy=200;game.stage2Boss.update(.016,game);assert.equal(game.stage2Boss.state,'slam-impact');assert(game.stage2Shockwaves.length>=2,'boss slam must emit ground shockwaves');assert(game.stage2BossEffects.at(-1).frame===3,'boss slam must create its generated impact eruption');drawImageCalls=[];game.stage2Shockwaves[0].draw(context2d);assert(drawImageCalls.some(args=>args[0]===SPRITES.stage2BossVfx&&args[1]===512&&args[2]===512),'loaded Stage 2 shockwave must draw generated frame 4');assert.equal(contextDepth,0,'Stage 2 shockwave drawing must balance canvas state');
game.stage2Boss.x=5600;game.stage2Boss.y=500;game.stage2Boss.vx=0;game.stage2Boss.vy=0;game.stage2Boss.dashTargetX=6100;game.stage2Boss.dashTargetY=500;game.stage2Boss.vfxTimer=.04;game.stage2Boss.setState('dash-windup',0);game.stage2Boss.update(.016,game);assert.equal(game.stage2Boss.state,'dash');assert.equal(game.stage2Boss.vfxTimer,0,'each Stage 2 dash must reset its trail timer');game.stage2Boss.update(.016,game);assert(game.stage2BossEffects.some(effect=>effect.frame===2),'Stage 2 dash must create generated afterimages immediately');
for(let i=0;i<50;i++)game.spawnStage2BossEffect(2,game.stage2Boss.cx,game.stage2Boss.cy,100,.3);assert(game.stage2BossEffects.length<=40,'boss VFX must stay capped during effect-heavy combat');const expiringEffect=game.stage2BossEffects.at(-1);expiringEffect.life=.001;game.updateStage2(.016);assert(!game.stage2BossEffects.includes(expiringEffect),'expired Stage 2 boss VFX must be removed');game.stage2BossEffects.length=0;
const bossStates=new Set();game.stage2Boss.x=5700;game.stage2Boss.y=520;game.stage2Boss.vx=0;game.stage2Boss.vy=0;game.stage2Boss.attack=0;game.stage2Boss.setState('recover',0);for(let i=0;i<1500;i++){game.stage2Boss.update(1/60,game);bossStates.add(game.stage2Boss.state);assert(Number.isFinite(game.stage2Boss.x)&&Number.isFinite(game.stage2Boss.y)&&Number.isFinite(game.stage2Boss.vx)&&Number.isFinite(game.stage2Boss.vy),'boss motion must stay finite');}for(const state of ['bolts-windup','dash-windup','slam-windup','slam-drop','slam-impact'])assert(bossStates.has(state),`boss combat loop must reach ${state} without stalling`);
game.stage2Projectiles.push({});game.stage2Shockwaves.push({});game.stage2Boss.kill(game);assert.equal(game.stage2Projectiles.length,0,'Stage 2 boss death must clear projectiles');assert.equal(game.stage2Shockwaves.length,0,'Stage 2 boss death must clear shockwaves');assert.equal(game.stage2BossEffects.length,1,'Stage 2 boss death must replace active effects with its finishing halo');assert.equal(game.stage2BossEffects[0].frame,5,'Stage 2 boss death must use the generated phase halo');drawImageCalls=[];game.stage2BossEffects[0].draw(context2d);assert(drawImageCalls.some(args=>args[0]===SPRITES.stage2BossVfx&&args[1]===1024&&args[2]===512),'loaded Stage 2 death halo must draw generated frame 5');assert.equal(contextDepth,0,'Stage 2 death halo drawing must balance canvas state');

game.mode='classic';game.reset();assert(game.player instanceof Player);assert.equal(game.encounterState,'clear-hostiles');

console.log('Mastra Vanguard smoke tests: PASS');
