import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';
import zlib from 'node:zlib';
import { fileURLToPath } from 'node:url';

const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const html=fs.readFileSync(path.join(root,'index.html'),'utf8');
const script=html.match(/<script>([\s\S]*?)<\/script>/)?.[1];
assert(script,'index.html must contain a game script');

for(const match of html.matchAll(/loadSprite\('([^']+)'/g))assert(fs.existsSync(path.join(root,match[1])),`missing sprite: ${match[1]}`);
assert(fs.existsSync(path.join(root,'Background OST.mp3')),'missing background OST');

const paeth=(a,b,c)=>{const p=a+b-c,pa=Math.abs(p-a),pb=Math.abs(p-b),pc=Math.abs(p-c);return pa<=pb&&pa<=pc?a:pb<=pc?b:c;};
function pngAlphaStats(png,columns=3,rows=2){
  const width=png.readUInt32BE(16),height=png.readUInt32BE(20);assert.equal(png[24],8,'VFX PNG must use 8-bit channels');assert.equal(png[25],6,'VFX PNG must use RGBA color');assert.equal(png[28],0,'VFX PNG must be non-interlaced');
  const chunks=[];for(let offset=8;offset+12<=png.length;){const length=png.readUInt32BE(offset),type=png.toString('ascii',offset+4,offset+8);if(type==='IDAT')chunks.push(png.subarray(offset+8,offset+8+length));offset+=length+12;if(type==='IEND')break;}
  const packed=zlib.inflateSync(Buffer.concat(chunks)),stride=width*4,previous=Buffer.alloc(stride),row=Buffer.alloc(stride),cellW=width/columns,cellH=height/rows,cells=Array.from({length:columns*rows},()=>({transparent:0,visible:0,edge:0}));assert.equal(packed.length,height*(stride+1),'unexpected VFX PNG scanline size');let cursor=0,transparent=0,visible=0;
  for(let y=0;y<height;y++){const filter=packed[cursor++];assert(filter>=0&&filter<=4,'unsupported PNG filter');for(let x=0;x<stride;x++){const raw=packed[cursor++],left=x>=4?row[x-4]:0,up=previous[x],upperLeft=x>=4?previous[x-4]:0,predictor=filter===0?0:filter===1?left:filter===2?up:filter===3?Math.floor((left+up)/2):paeth(left,up,upperLeft);row[x]=(raw+predictor)&255;}for(let x=3;x<stride;x+=4){const pixelX=(x-3)/4,frame=Math.min(cells.length-1,Math.floor(pixelX/cellW)+columns*Math.floor(y/cellH)),cellX=pixelX%cellW,cellY=y%cellH;if(row[x]===0){transparent++;cells[frame].transparent++;}else{visible++;cells[frame].visible++;if(cellX===0||cellY===0||cellX===cellW-1||cellY===cellH-1)cells[frame].edge++;}}previous.set(row);}
  return{width,height,transparent,visible,cells};
}

class MockElement {
  constructor(id=''){this.id=id;this.value='0';this.textContent='';this.inert=false;this.attributes=new Map();this.classList={toggle(){},add(){},remove(){}};}
  addEventListener(){} setAttribute(k,v){this.attributes.set(k,String(v));} closest(){return null;} contains(){return false;} focus(){} requestFullscreen(){document.fullscreenElement=this;}
}

let saveCalls=0,contextDepth=0,drawImageCalls=[];
const gradient={addColorStop(){}};
const context2d=new Proxy({
  setTransform(){},createLinearGradient(){return gradient;},save(){saveCalls++;contextDepth++;},restore(){contextDepth--;if(contextDepth<0)throw new Error('canvas restore without save');},drawImage(...args){drawImageCalls.push(args);},measureText(){return{width:0}}
},{get(target,key){if(key in target)return target[key];return()=>{};},set(target,key,value){target[key]=value;return true;}});
const elements=new Map();
const canvas=new MockElement('game');canvas.width=0;canvas.height=0;canvas.style={};canvas.getContext=()=>context2d;canvas.getBoundingClientRect=()=>({left:0,top:0});
elements.set('game',canvas);
const element=id=>{if(!elements.has(id))elements.set(id,new MockElement(id));return elements.get(id);};

const storage=new Map();
const document={
  activeElement:null,hidden:false,fullscreenElement:null,documentElement:new MockElement('documentElement'),
  getElementById:element,addEventListener(){},exitFullscreen(){this.fullscreenElement=null;}
};
const localStorage={getItem:key=>storage.get(key)??null,setItem:(key,value)=>storage.set(key,String(value))};
class MockImage {constructor(){this.complete=false;this.naturalWidth=0;this.naturalHeight=0;this.listeners=new Map();this._src='';}addEventListener(type,fn){this.listeners.set(type,fn);}set src(value){this._src=value;}get src(){return this._src;}}
class MockAudio {constructor(src){this.src=src;this.loop=false;this.preload='';this.volume=1;this.muted=false;this.paused=true;}play(){this.paused=false;return Promise.resolve();}pause(){this.paused=true;}}
class MockAudioContext {
  constructor(){this.currentTime=0;this.state='running';this.destination={};}
  resume(){this.state='running';return Promise.resolve();}
  createGain(){return{gain:{value:1,setValueAtTime(){},exponentialRampToValueAtTime(){}},connect(){return this;},disconnect(){}};}
  createOscillator(){return{type:'sine',frequency:{setValueAtTime(){},exponentialRampToValueAtTime(){}},connect(){return this;},disconnect(){},start(){},stop(){},addEventListener(){}};}
}

const sandbox={
  console,Math,JSON,Number,Boolean,Set,Map,Object,Array,String,Date,Error,Promise,
  innerWidth:1280,innerHeight:720,devicePixelRatio:1,performance:{now:()=>1000},
  document,localStorage,Image:MockImage,Audio:MockAudio,AudioContext:MockAudioContext,webkitAudioContext:MockAudioContext,
  Element:MockElement,addEventListener(){},requestAnimationFrame(){},setTimeout,clearTimeout
};
sandbox.window=sandbox; sandbox.globalThis=sandbox;
vm.createContext(sandbox);
vm.runInContext(`${script}\n;globalThis.__test={CFG,STAGE2,STAGE3,SPRITES,AudioFX,PrismWarden,Player,GroundEnemy,Stage2Hero,CrystalStalker,SporeDrone,AstralDevourer,Stage3Hero,Stage3Platform,Stage3Projectile,Stage3Shockwave,FoundryHazard,HeliarchSweep,SolarLegionnaire,FluxManta,ForgeWeaver,HeliarchZero,rayRect,game};`,sandbox,{filename:'index.html'});

const {CFG,STAGE2,STAGE3,SPRITES,AudioFX,PrismWarden,Player,GroundEnemy,Stage2Hero,CrystalStalker,SporeDrone,AstralDevourer,Stage3Hero,Stage3Platform,Stage3Projectile,Stage3Shockwave,FoundryHazard,HeliarchSweep,SolarLegionnaire,FluxManta,ForgeWeaver,HeliarchZero,rayRect,game}=sandbox.__test;
const {SIM_STEP,DisplaySettings,Stage2Platform,Particle,HostileProjectile,stageAssets,readySprite,interpolateRenderBody,restoreRenderBody}=vm.runInContext('({SIM_STEP,DisplaySettings,Stage2Platform,Particle,HostileProjectile,stageAssets,readySprite,interpolateRenderBody,restoreRenderBody})',sandbox);
const markSpriteLoaded=image=>Object.assign(image,{complete:true,naturalWidth:1536,naturalHeight:1024,width:1536,height:1024});
game.audio.muted=true;

assert(!html.includes('desynchronized:true'),'the shared canvas must use synchronized presentation so the HUD cannot tear or flicker');
assert(!/urgent&&Math\.floor\(performance\.now\(\)\/180\)/.test(html),'low-resource HUD bars must use a steady warning treatment instead of flashing');
assert.equal(CFG.ultimateMaxCharges,3);
assert.equal(CFG.ultimateRadius,660);
assert.equal(CFG.flightVerticalResponse,.82,'flight vertical response must remain tuned for smooth acceleration');
assert.equal(CFG.flightDescentResponse,1.12,'flight descent response must build speed faster while staying capped');
assert.equal(CFG.flightLandingShockwaveSpeed,1600,'landing shockwave must require true boosted-flight impact speed');
assert(/id="classicMode"[\s\S]*?<h2>STAGE 1<\/h2>/.test(html),'the original campaign must be labeled Stage 1 in the player-facing menu');
for(const [asset,columns] of [['astra-walk-frames-v3.png',4],['astra-sprint-frames-v1.png',4]]){const alpha=pngAlphaStats(fs.readFileSync(path.join(root,'assets','sprites',asset)),columns,2),pixels=alpha.width*alpha.height;assert(alpha.transparent>pixels*.2&&alpha.visible>pixels*.2,`${asset} must have a true transparent background`);for(const [frame,cell] of alpha.cells.entries())assert(cell.transparent>1000&&cell.visible>1000,`${asset} frame ${frame} must contain transparent space and character art`);}
const idleAlpha=pngAlphaStats(fs.readFileSync(path.join(root,'assets','sprites','astra-idle-cape-frames-v4.png')),2,2),idlePixels=idleAlpha.width*idleAlpha.height;assert(idleAlpha.transparent>idlePixels*.2&&idleAlpha.visible>idlePixels*.2,'cape-only idle sheet must have a true transparent background');for(const [frame,cell] of idleAlpha.cells.entries())assert(cell.transparent>1000&&cell.visible>1000,`cape-only idle frame ${frame} must contain transparent space and character art`);
const machLandingAlpha=pngAlphaStats(fs.readFileSync(path.join(root,'assets','sprites','astra-mach-landing-vfx-frames-v1.png')),2,2),machLandingPixels=machLandingAlpha.width*machLandingAlpha.height;assert.equal(machLandingAlpha.width,1536);assert.equal(machLandingAlpha.height,1024);assert(machLandingAlpha.transparent>machLandingPixels*.2&&machLandingAlpha.visible>machLandingPixels*.2,'generated Mach landing sheet must contain genuine transparency and visible VFX');for(const [frame,cell] of machLandingAlpha.cells.entries())assert(cell.transparent>1000&&cell.visible>1000,`generated Mach landing frame ${frame} must contain transparent space and effect artwork`);

game.mode='classic';game.started=true;game.reset();game.audio.muted=true;
assert.equal(game.player.launchDuration,.6,'power-launch charge must last 0.60 seconds');
game.player.onGround=true;game.player.updateJumpAssist(.016,game);game.player.onGround=false;game.input.pressed.add('w');game.player.updateJumpAssist(.016,game);assert(game.player.coyoteTimer>0,'leaving a rooftop must preserve a short coyote-time window');assert(game.player.tryBufferedJump(game),'coyote-time jump must execute after stepping off a rooftop');assert.equal(game.player.vy,-CFG.jumpSpeed);game.input.clear();game.reset();game.player.onGround=false;game.input.pressed.add('w');game.player.updateJumpAssist(.016,game);assert(game.player.jumpBufferTimer>0,'an early jump press must enter the jump buffer');game.player.onGround=true;assert(game.player.tryBufferedJump(game),'buffered jump must execute on landing');game.input.clear();game.reset();game.player.onGround=true;assert.equal(game.powerLaunchStatus(game.player).label,'READY');game.player.energy=0;assert.equal(game.powerLaunchStatus(game.player).label,'LOW FLIGHT ENERGY');game.player.energy=CFG.maxEnergy;game.player.launchCharging=true;game.player.launchTimer=.3;assert.equal(game.powerLaunchStatus(game.player).label,'CHARGING 50%');game.reset();
markSpriteLoaded(SPRITES.astraFlight);markSpriteLoaded(SPRITES.astraFlightUp);markSpriteLoaded(SPRITES.astraFlightDown);game.player.onGround=true;game.input.pressed.add('f');game.player.update(.016,game);assert.equal(game.player.flying,true,'F must enable flight');drawImageCalls=[];game.player.draw(context2d,game);assert(drawImageCalls.some(args=>args[0]===SPRITES.astraFlight),'toggling F must use the default sideways flight animation');assert(!drawImageCalls.some(args=>args[0]===SPRITES.astraFlightUp||args[0]===SPRITES.astraFlightDown),'F toggle alone must not select a vertical flight pose');game.input.clear();game.player.vx=0;game.player.vy=-CFG.flyMax;game.input.keys.add('w');drawImageCalls=[];game.player.draw(context2d,game);assert(drawImageCalls.some(args=>args[0]===SPRITES.astraFlightUp),'active ascent must use the straight-up flight pose');game.input.clear();game.player.vy=CFG.flyMax;game.input.keys.add('s');drawImageCalls=[];game.player.draw(context2d,game);assert(drawImageCalls.some(args=>args[0]===SPRITES.astraFlightDown),'active descent must use the straight-down flight pose');game.input.clear();game.reset();
game.player.flying=true;game.player.vx=0;game.player.vy=0;game.player.updateFlightVelocity(.016,0,1,CFG.flyAccel,CFG.flyMax);const descentStep=game.player.vy;assert(descentStep>0&&descentStep<CFG.flyMax*.1,'flight descent must ease toward its target instead of snapping to max speed');game.player.vy=0;game.player.updateFlightVelocity(.016,0,-1,CFG.flyAccel,CFG.flyMax);assert(game.player.vy<0&&Math.abs(game.player.vy)<descentStep,'flight direction changes must decelerate smoothly without overshooting');game.player.vy=500;game.player.updateFlightVelocity(.016,0,-1,CFG.flyAccel,CFG.flyMax);assert(game.player.vy>0&&game.player.vy<500,'flight reversals must bleed speed smoothly instead of flipping direction in one frame');game.player.flying=false;
game.launchWaves.length=0;const landingTarget=game.enemies[0],landingTargetHp=landingTarget.hp,machImpact=CFG.flightLandingShockwaveSpeed+100;game.player.onGround=false;game.player.y=1253.5;game.player.vy=machImpact;game.player.speedBuild=CFG.sonicThreshold;game.player.sonicBoomTriggered=true;game.player.update(.016,game);assert(game.player.onGround,'a Mach descent test must land on the Stage One floor');const landingWave=game.launchWaves.find(w=>w.impact);assert(landingWave,'a Mach-speed landing must create an impact shockwave');assert(landingWave.damage>0&&landingWave.damageRadius>0,'landing shockwave must carry explicit radial damage');assert(landingTarget.hp<landingTargetHp,'a nearby Stage One enemy must take landing shockwave damage');markSpriteLoaded(SPRITES.astraMachLanding);drawImageCalls=[];game.draw();assert(drawImageCalls.some(args=>args[0]===SPRITES.astraMachLanding),'Mach landing must render the generated four-frame VFX sheet');assert.equal(contextDepth,0,'custom landing shockwave graphics must balance canvas state');game.launchWaves.length=0;const controlledTargetHp=landingTarget.hp;game.player.onGround=false;game.player.y=1253.5;game.player.vy=machImpact;game.player.speedBuild=0;game.player.sonicBoomTriggered=false;game.player.update(.016,game);assert(game.player.onGround,'a non-Mach fast descent test must land on the Stage One floor');assert(!game.launchWaves.some(w=>w.impact),'speed alone must not create a landing shockwave without reaching Mach state');assert.equal(landingTarget.hp,controlledTargetHp,'a non-Mach landing must not deal shockwave damage');game.reset();
game.player.onGround=true;game.player.vx=CFG.runMax;game.player.updateLocomotion(.12);assert(game.player.groundMotion>.7,'Astra must smoothly enter the upgraded walk cycle');markSpriteLoaded(SPRITES.astraWalk);markSpriteLoaded(SPRITES.astraSprint);drawImageCalls=[];game.player.draw(context2d,game);assert(drawImageCalls.some(args=>args[0]===SPRITES.astraWalk),'Astra walking must use the dedicated eight-frame walk sheet');game.player.boosting=true;game.player.updateLocomotion(.12);assert(game.player.sprintMotion>.7,'Astra must smoothly enter the upgraded sprint cycle');drawImageCalls=[];game.player.draw(context2d,game);assert(drawImageCalls.some(args=>args[0]===SPRITES.astraSprint),'Astra sprinting must use the dedicated eight-frame sprint sheet without frame blending');game.player.onGround=false;game.player.boosting=false;game.player.updateLocomotion(.25);assert(game.player.groundMotion<.1&&game.player.sprintMotion<.1,'Astra locomotion must smoothly settle when leaving the ground');game.player.vx=0;
game.reset();game.player.onGround=true;game.input.keys.add('shift');game.input.keys.add('w');game.player.update(.016,game);assert(game.player.launchCharging,'Shift + W must begin a grounded power-launch charge');assert.equal(game.player.vx,0,'power-launch charge must lock horizontal movement');game.player.draw(context2d,game);assert.equal(contextDepth,0,'power-launch charge drawing must balance canvas state');game.input.keys.delete('w');game.player.update(.016,game);assert.equal(game.player.launchCharging,false,'releasing the combo during charge must cancel cleanly');assert.equal(game.player.flying,false,'cancelled power launch must not toggle flight');game.input.clear();game.reset();game.player.onGround=true;game.input.keys.add('shift');game.input.keys.add('w');for(let i=0;i<30;i++)game.player.update(1/30,game);assert.equal(game.player.flying,true,'completed power launch must enable flight');assert.equal(game.player.speedBuild,1,'power launch must start at maximum boost build');assert(Math.hypot(game.player.vx,game.player.vy)>CFG.speedFlyMax*.95,'power launch must use maximum boosted flight speed');assert(game.launchWaves.length===1,'power launch must create one takeoff shockwave');game.player.draw(context2d,game);assert.equal(contextDepth,0,'power-launch burst drawing must balance canvas state');game.input.clear();
assert.equal(game.player.vx,0,'completed power launch must travel perfectly straight upward');
assert.equal(game.player.vy,-CFG.speedFlyMax,'completed power launch must use maximum boosted flight speed vertically');
game.reset();game.player.onGround=true;game.input.keys.add('d');game.player.update(.08,game);assert(game.player.x>game.player.spawnX,'normal grounded movement must remain available after power-launch integration');game.input.clear();
const wardenVfxPng=fs.readFileSync(path.join(root,'assets','sprites','prism-warden-vfx-frames-v1.png')),wardenAlpha=pngAlphaStats(wardenVfxPng),wardenPixels=wardenAlpha.width*wardenAlpha.height;assert.equal(wardenAlpha.width,1536);assert.equal(wardenAlpha.height,1024);assert(wardenAlpha.transparent>wardenPixels*.2&&wardenAlpha.visible>wardenPixels*.2,'Prism Warden VFX must contain genuine transparent and visible pixels');for(const [frame,cell] of wardenAlpha.cells.entries())assert(cell.transparent>1000&&cell.visible>1000,`Prism Warden VFX frame ${frame} must contain transparency and artwork`);assert.equal(game.wardenEffects.length,0,'classic mode must reset Warden effects');
game.input.keys.add(' ');game.input.pressed.add(' ');
game.player.updateBeamCharge(.4,game);
game.input.pressed.clear();game.input.keys.delete(' ');game.input.released.add(' ');
game.player.updateBeamCharge(.016,game);
assert.equal(game.player.chargingBeam,false,'releasing Space must end beam charging');
assert.equal(game.beams.length,1,'releasing a charged Space must fire one super beam');
const classicSuperBeam=game.beams[0];assert(Math.hypot(classicSuperBeam.ex-classicSuperBeam.x,classicSuperBeam.ey-classicSuperBeam.y)>=CFG.superBeamRange*.99,'Stage One Super Beam must span the full screen and world direction');assert.equal(classicSuperBeam.life,classicSuperBeam.max,'Super Beam must begin at full visual intensity');

game.reset();const classicTarget=game.enemies[0],classicSecondTarget=game.enemies[1],classicOrigin=game.player.beamOrigin(),classicTargetHp=classicTarget.hp,classicSecondTargetHp=classicSecondTarget.hp;classicTarget.x=classicOrigin.x+280;classicTarget.y=classicOrigin.y-classicTarget.h/2;classicSecondTarget.x=classicOrigin.x+610;classicSecondTarget.y=classicOrigin.y-classicSecondTarget.h/2;game.input.mouse.x=classicTarget.x+classicTarget.w/2-game.camera.x;game.input.mouse.y=classicTarget.y+classicTarget.h/2-game.camera.y;game.input.mouse.down=true;game.player.update(.016,game);assert(game.heatVision,'Stage One must use Astra’s continuous heat vision');assert.equal(game.beams.length,0,'held heat vision must not create Stage One projectile shots');assert(Math.hypot(game.heatVision.ex-game.heatVision.x,game.heatVision.ey-game.heatVision.y)>=CFG.heatVisionRange*.99,'Stage One heat vision must reach beyond the visible map');assert(classicTarget.hp<classicTargetHp&&classicSecondTarget.hp<classicSecondTargetHp,'Stage One heat vision must pierce every target in its path');game.input.mouse.down=false;game.player.update(.016,game);assert.equal(game.heatVision,null,'releasing the primary beam must clear Stage One heat vision');game.input.clear();
assert(game.shake<.04,'continuous heat vision must use subtle frame-rate-independent camera shake');
const visibleTrooper=game.enemies[0],upperBodyBeamY=visibleTrooper.y-12;assert.equal(rayRect(0,upperBodyBeamY,1,0,visibleTrooper,CFG.heatVisionRange),null,'the old compact trooper physics box must not mask this regression');assert.notEqual(rayRect(0,upperBodyBeamY,1,0,visibleTrooper.beamHitbox(),CFG.heatVisionRange),null,'the rendered trooper torso must be hittable by a beam');
game.reset();const beamTrooper=game.enemies[0],beamOrigin=game.player.beamOrigin(),beamTrooperHp=beamTrooper.hp;beamTrooper.x=beamOrigin.x+320;beamTrooper.y=beamOrigin.y+18;game.input.mouse.x=beamTrooper.x+beamTrooper.w/2-game.camera.x;game.input.mouse.y=beamOrigin.y-game.camera.y;game.input.mouse.down=true;game.player.update(.016,game);assert(beamTrooper.hp<beamTrooperHp,'continuous heat vision must damage a visible trooper upper body outside its movement box');game.input.mouse.down=false;game.input.clear();

game.startBossIntro();const boss=game.boss,wardenIntroEffect=game.wardenEffects.find(effect=>effect.frame===5&&effect.layer==='behind');assert(boss instanceof PrismWarden);assert(wardenIntroEffect,'Warden intro must create its generated phase halo');assert(wardenIntroEffect.life>=game.encounterTimer,'Warden intro halo must cover the full entrance');const wardenBossX=boss.x;boss.x+=24;wardenIntroEffect.update(0,game);assert.equal(wardenIntroEffect.x,boss.cx,'Warden intro halo must follow the moving boss');boss.x=wardenBossX;wardenIntroEffect.update(0,game);markSpriteLoaded(SPRITES.wardenVfx);drawImageCalls=[];wardenIntroEffect.draw(context2d);assert(drawImageCalls.some(args=>args[0]===SPRITES.wardenVfx&&args[1]===1024&&args[2]===512),'loaded Warden halo must draw generated frame 5');assert.equal(contextDepth,0,'Warden halo drawing must balance canvas state');game.encounterState='boss-fight';boss.phase=2;boss.hp=1000;boss.attackSerial=0;boss.facing=1;game.player.x=4720;
const wardenProjectileCount=game.projectiles.length,wardenEffectCount=game.wardenEffects.length;boss.fireVolley(game);assert(game.projectiles.length>wardenProjectileCount,'Warden volley must create projectiles');assert(game.projectiles[wardenProjectileCount].x>boss.cx,'Warden bolts must originate from its visible cannon');assert(game.wardenEffects.length>wardenEffectCount&&game.wardenEffects.at(-1).frame===0,'Warden volley must create its generated muzzle effect');drawImageCalls=[];game.projectiles.at(-1).draw(context2d);assert(drawImageCalls.some(args=>args[0]===SPRITES.wardenVfx&&args[1]===0&&args[2]===0),'loaded Warden bolt must draw generated frame 0');assert.equal(contextDepth,0,'Warden projectile drawing must balance canvas state');boss.setState('ranged',0);boss.update(.016,game);assert.equal(boss.state,'ranged-fire','Warden must hold its cannon firing frame when the volley launches');assert.equal(boss.animationFrame().frame,4,'Warden firing state must use the muzzle-flash frame');boss.stateTimer=0;boss.update(.016,game);assert.equal(boss.state,'recover');
boss.chooseAttack(game);assert.equal(boss.state,'slam-windup');assert(boss.slamLiftY<=boss.slamTargetY,'slam windup must remain above its landing point');
boss.stateTimer=0;boss.update(.016,game);assert.equal(boss.state,'slam-drop');assert(boss.slamTargetY>=boss.slamStartY,'slam drop must never interpolate upward');boss.stateTimer=0;boss.update(.016,game);assert.equal(boss.state,'slam-impact');assert(game.wardenEffects.at(-1).frame===3,'Warden slam must create its generated crystal impact');drawImageCalls=[];game.shockwaves[0].draw(context2d);assert(drawImageCalls.some(args=>args[0]===SPRITES.wardenVfx&&args[1]===512&&args[2]===512),'loaded Warden shockwave must draw generated frame 4');assert.equal(contextDepth,0,'Warden shockwave drawing must balance canvas state');
boss.x=4300;boss.y=700;boss.vx=0;boss.vy=0;boss.vfxTimer=.04;boss.setState('dash-windup',0);game.player.x=4800;boss.update(.016,game);assert.equal(boss.state,'dash');assert.equal(boss.vfxTimer,0,'each Warden dash must reset its trail timer');boss.update(.016,game);assert(game.wardenEffects.some(effect=>effect.frame===2),'Warden dash must create generated afterimages immediately');for(let i=0;i<50;i++)game.spawnWardenEffect(2,boss.cx,boss.cy,100,.3);assert(game.wardenEffects.length<=40,'Warden VFX must stay capped during effect-heavy combat');const expiringWardenEffect=game.wardenEffects.at(-1);expiringWardenEffect.life=.001;game.update(.016);assert(!game.wardenEffects.includes(expiringWardenEffect),'expired Warden VFX must be removed');

game.projectiles.push({});game.shockwaves.push({});boss.kill(game);
assert.equal(game.projectiles.length,0,'boss death must clear projectiles');
assert.equal(game.shockwaves.length,0,'boss death must clear shockwaves');
assert.equal(game.wardenEffects.length,1,'Warden death must replace active effects with its finishing halo');assert.equal(game.wardenEffects[0].frame,5,'Warden death must use the generated phase halo');

game.reset();const fallen=new GroundEnemy(100,CFG.worldH+100);fallen.update(.016,game);assert.equal(fallen.dead,true,'fallen enemies must not block stage progression');

game.mode='god';game.reset();game.player.y=CFG.worldH+100;game.player.update(.016,game);
assert.equal(game.player.y,game.player.spawnY,'God Mode must recover from the void');
game.player.flying=true;game.player.y=-80;game.player.vy=-300;game.player.update(.016,game);
assert.equal(game.player.y,20,'player must remain inside the top world boundary');

game.player.dead=true;game.player.invuln=1;game.player.deathAt=sandbox.performance.now();saveCalls=0;game.player.draw(context2d,game);
assert(saveCalls>0,'death animation must render even while invulnerability is active');

game.mode='classic';game.reset();game.started=true;game.player.dead=true;game.input.pressed.add('escape');game.update(.016);
assert.equal(game.paused,true,'Escape must open the menu after death');
game.input.keys.add('shift');game.projectiles.push({});game.restart();
assert.equal(game.input.keys.size,0,'restart must clear held input');assert.equal(game.projectiles.length,0,'restart must clear active attacks');assert.equal(game.player.dead,false);

game.particles.length=0;game.burst(0,0,'#fff',Number.MAX_SAFE_INTEGER,100);assert.equal(game.particles.length,520,'particle count must be capped');

game.audio.setMusicVolume(.23);game.audio.setSfxVolume(.41);game.audio.setMuted(true);
const restoredAudio=new AudioFX();assert.equal(restoredAudio.musicVolume,.23);assert.equal(restoredAudio.sfxVolume,.41);assert.equal(restoredAudio.muted,true);

game.mode='stage2';game.started=true;game.audio.muted=true;game.resetStage2();
assert.equal(STAGE2.worldW,6400);assert.equal(game.stage2Platforms.length,13);assert.equal(game.stage2Enemies.length,10);assert(game.stage2Hero instanceof Stage2Hero);assert(game.stage2Hero instanceof Player,'Stage Two must use the same Astra character system');assert.equal(game.stage2Hero.w,CFG.playerW);assert.equal(game.stage2Hero.ultimateCharges,CFG.ultimateMaxCharges);assert(game.stage2Enemies.some(enemy=>enemy instanceof CrystalStalker));assert(game.stage2Enemies.some(enemy=>enemy instanceof SporeDrone));
game.stage2Hero.onGround=true;game.input.keys.add('shift');game.input.keys.add('w');for(let i=0;i<30;i++)game.stage2Hero.update(1/30,game);assert.equal(game.stage2Hero.flying,true,'Stage Two must use the same power-launch flight burst');assert.equal(game.stage2Hero.speedBuild,1,'Stage Two power launch must start at maximum boost build');assert(game.stage2LaunchWaves.length===1,'Stage Two power launch must create a takeoff shockwave');game.input.clear();game.resetStage2();game.stage2LaunchWaves.length=0;const stage2LandingTarget=game.stage2Enemies[0];stage2LandingTarget.x=160;stage2LandingTarget.y=1382;const stage2LandingHp=stage2LandingTarget.hp;game.stage2Hero.flying=false;game.stage2Hero.onGround=false;game.stage2Hero.y=1383.5;game.stage2Hero.vy=machImpact;game.stage2Hero.speedBuild=CFG.sonicThreshold;game.stage2Hero.sonicBoomTriggered=true;game.stage2Hero.update(.016,game);assert(game.stage2Hero.onGround,'Stage Two Mach descent must land on its floor');assert(game.stage2LaunchWaves.some(w=>w.impact),'Stage Two Mach landing must create an impact shockwave');assert(stage2LandingTarget.hp<stage2LandingHp,'Stage Two landing shockwave must damage a nearby enemy');game.stage2LaunchWaves.length=0;game.stage2Hero.onGround=false;game.stage2Hero.y=1383.5;game.stage2Hero.vy=machImpact;game.stage2Hero.speedBuild=0;game.stage2Hero.sonicBoomTriggered=false;game.stage2Hero.update(.016,game);assert(game.stage2Hero.onGround,'Stage Two non-Mach fast descent must land on its floor');assert(!game.stage2LaunchWaves.some(w=>w.impact),'Stage Two speed alone must not create a shockwave without Mach state');game.resetStage2();
game.input.mouse.x=game.w;game.input.mouse.y=game.h*.5;game.stage2Hero.fireSuperBeam(game,1);assert.equal(game.stage2Beams.length,1,'Stage Two must inherit the shared Super Beam');const stage2SuperBeam=game.stage2Beams[0];assert(Math.hypot(stage2SuperBeam.ex-stage2SuperBeam.x,stage2SuperBeam.ey-stage2SuperBeam.y)>=CFG.superBeamRange*.99,'Stage Two Super Beam must span the full screen and world direction');game.resetStage2();
game.stage2Hero.onGround=true;game.stage2Hero.vx=CFG.runMax;game.stage2Hero.boosting=true;game.stage2Hero.updateLocomotion(.12);assert(game.stage2Hero.groundMotion>.7&&game.stage2Hero.sprintMotion>.7,'Stage Two must inherit Astra’s upgraded locomotion system');game.stage2Hero.vx=0;game.stage2Hero.boosting=false;
game.stage2Hero.onGround=true;const stage2StartX=game.stage2Hero.x;game.input.keys.add('d');game.stage2Hero.update(.08,game);assert(game.stage2Hero.x>stage2StartX,'Stage Two normal grounded movement must remain available after power-launch integration');game.input.clear();
assert(game.stage2Platforms.some(platform=>platform.x<=game.stage2ArenaLeft&&platform.x+platform.w>=STAGE2.worldW&&platform.y===1450),'boss arena must have one continuous floor');
for(const facade of game.stage2Platforms.filter(platform=>platform.facade))assert(game.stage2Platforms.some(base=>!base.facade&&base.y===facade.y+facade.h&&base.x<=facade.x&&base.x+base.w>=facade.x+facade.w),`facade at ${facade.x} must be fully supported by its floor`);
for(const asset of ['stage2-crystal-stalker-frames-v1.png','stage2-spore-drone-frames-v1.png','stage2-astral-devourer-frames-v2.png','stage2-boss-vfx-frames-v1.png']){const png=fs.readFileSync(path.join(root,'assets','sprites',asset));assert.equal(png[25],6,`${asset} must retain PNG alpha transparency`);if(asset==='stage2-boss-vfx-frames-v1.png'){const alpha=pngAlphaStats(png),pixels=alpha.width*alpha.height;assert.equal(alpha.width,1536);assert.equal(alpha.height,1024);assert(alpha.transparent>pixels*.2&&alpha.visible>pixels*.2,'Stage 2 boss VFX must contain genuine transparent and visible pixels');for(const [frame,cell] of alpha.cells.entries())assert(cell.transparent>1000&&cell.visible>1000,`Stage 2 boss VFX frame ${frame} must contain transparency and artwork`);}}
const openingEnemy=game.stage2Enemies[0],openingAnim=openingEnemy.anim,openingX=openingEnemy.x,openingHp=game.stage2Hero.hp;for(let i=0;i<60;i++)game.update(1/60);assert(openingEnemy.anim>openingAnim&&openingEnemy.x>openingX+20,'Stage Two enemies must patrol and animate during the opening card');assert.equal(game.stage2Hero.hp,openingHp,'opening patrol movement must not damage Astra before combat aggro begins');
const facadeWalker=new CrystalStalker(830,1382);facadeWalker.attackCd=99;facadeWalker.moveDir=1;facadeWalker.vx=120;game.stage2Hero.x=1160;game.stage2Hero.y=1384;for(let i=0;i<120;i++)facadeWalker.update(1/60,game);assert(facadeWalker.x>930,'ground stalkers must cross decorative facades instead of getting pinned against them');
const edgeWalker=new CrystalStalker(1250,1382);edgeWalker.attackCd=99;edgeWalker.moveDir=1;edgeWalker.vx=120;game.stage2Hero.x=3000;for(let i=0;i<90;i++)edgeWalker.update(1/60,game);assert(edgeWalker.x<1230&&edgeWalker.moveDir<0,'stalkers must commit to a ledge turn instead of oscillating in place');game.stage2Hero.x=120;game.stage2Hero.y=1450-CFG.playerH;
const stage2Target=game.stage2Enemies[0],stage2SecondTarget=game.stage2Enemies[1],stage2Origin=game.stage2Hero.beamOrigin(),stage2TargetHp=stage2Target.hp,stage2SecondTargetHp=stage2SecondTarget.hp;stage2Target.x=stage2Origin.x+280;stage2Target.y=stage2Origin.y-stage2Target.h/2;stage2SecondTarget.x=stage2Origin.x+610;stage2SecondTarget.y=stage2Origin.y-stage2SecondTarget.h/2;game.input.mouse.x=stage2Target.x+stage2Target.w/2-game.camera.x;game.input.mouse.y=stage2Target.y+stage2Target.h/2-game.camera.y;game.input.mouse.down=true;game.stage2Hero.update(.016,game);assert(game.stage2HeatVision,'holding the primary beam must create continuous heat vision');assert.equal(game.stage2Beams.length,0,'held heat vision must not create repeated projectile shots');assert(Math.hypot(game.stage2HeatVision.ex-game.stage2HeatVision.x,game.stage2HeatVision.ey-game.stage2HeatVision.y)>=STAGE2.heatVisionRange*.99,'heat vision must extend past the visible map');assert(stage2Target.hp<stage2TargetHp,'continuous heat vision must damage its first target');assert(stage2SecondTarget.hp<stage2SecondTargetHp,'heat vision must pierce targets instead of stopping at the first one');game.input.mouse.down=false;game.input.clear();
const stage2Charges=game.stage2Hero.ultimateCharges;game.stage2Hero.castUltimate(game);assert.equal(game.stage2Hero.ultimateCharges,stage2Charges-1,'Stage Two must retain Prism Nova');assert(game.stage2Waves.length>0);
game.draw();game.update(.016);assert.equal(game.stage2Encounter,'clear-hostiles');
game.stage2Enemies.length=0;game.stage2Hero.x=5200;game.update(.016);const stage2IntroEffect=game.stage2BossEffects.find(effect=>effect.frame===5&&effect.layer==='behind');assert.equal(game.stage2Encounter,'boss-intro');assert(game.stage2Boss instanceof AstralDevourer);assert(stage2IntroEffect,'boss intro must create its generated phase-halo effect');assert(stage2IntroEffect.life>=game.stage2Timer,'Stage 2 intro halo must cover the full entrance');const stage2IntroBossX=game.stage2Boss.x;game.stage2Boss.x+=30;stage2IntroEffect.update(0,game);assert.equal(stage2IntroEffect.x,game.stage2Boss.cx,'Stage 2 intro halo must follow the moving boss');game.stage2Boss.x=stage2IntroBossX;stage2IntroEffect.update(0,game);markSpriteLoaded(SPRITES.stage2BossVfx);drawImageCalls=[];stage2IntroEffect.draw(context2d);assert(drawImageCalls.some(args=>args[0]===SPRITES.stage2BossVfx&&args[1]===1024&&args[2]===512),'loaded Stage 2 halo must draw generated frame 5');assert.equal(contextDepth,0,'Stage 2 halo drawing must balance canvas state');
game.stage2Timer=0;game.update(.016);assert.equal(game.stage2Encounter,'boss-fight');game.stage2Boss.hit(100,game);assert(game.stage2Boss.hp<game.stage2Boss.maxHp);
game.stage2Boss.x=5700;game.stage2Hero.x=5200;const bossBoltCount=game.stage2Projectiles.length,bossEffectCount=game.stage2BossEffects.length;game.stage2Boss.fireBolts(game);const leftBolts=game.stage2Projectiles.slice(bossBoltCount);assert(leftBolts.length&&leftBolts.every(projectile=>projectile.kind==='boss-bolt'),'boss bolts must use generated VFX projectiles');assert(leftBolts[0].x<game.stage2Boss.cx,'left-facing boss bolts must originate from the visible left cannon');assert(game.stage2BossEffects.length>bossEffectCount&&game.stage2BossEffects.at(-1).frame===0,'boss volley must create a generated muzzle effect');drawImageCalls=[];leftBolts[0].draw(context2d);assert(drawImageCalls.some(args=>args[0]===SPRITES.stage2BossVfx&&args[1]===0&&args[2]===0),'loaded Stage 2 bolt must draw generated frame 0');assert.equal(contextDepth,0,'Stage 2 projectile drawing must balance canvas state');game.stage2Hero.x=6100;const rightBoltCount=game.stage2Projectiles.length;game.stage2Boss.fireBolts(game);assert(game.stage2Projectiles[rightBoltCount].x>game.stage2Boss.cx,'right-facing boss bolts must originate from the visible right cannon');game.stage2Hero.x=5350;
const bossPulseCount=game.stage2Projectiles.length;game.stage2Boss.firePulse(game);assert(game.stage2Projectiles.length>bossPulseCount&&game.stage2Projectiles.slice(bossPulseCount).every(projectile=>projectile.kind==='boss-pulse'),'boss pulse must use generated radial projectiles');assert(game.stage2BossEffects.at(-1).frame===1&&game.stage2BossEffects.at(-1).layer==='behind','boss pulse must create its generated radial sigil');
game.stage2Boss.phase=1;game.stage2Boss.hp=game.stage2Boss.maxHp*.5;game.stage2Boss.vx=240;game.stage2Boss.vy=0;game.stage2Boss.setState('recover',1);game.stage2Boss.update(.016,game);const stage2PhaseEffect=game.stage2BossEffects.at(-1);assert(stage2PhaseEffect.frame===5&&stage2PhaseEffect.followBoss,'Stage 2 phase halo must follow the drifting boss');game.stage2Boss.x+=28;stage2PhaseEffect.update(0,game);assert.equal(stage2PhaseEffect.x,game.stage2Boss.cx,'Stage 2 phase halo must stay centered on the boss');
game.stage2Hero.x=game.stage2ArenaLeft-100;game.update(.016);assert(game.stage2Hero.x>=game.stage2ArenaLeft+18,'boss barrier must lock behind Astra');
game.stage2Boss.x=5600;game.stage2Boss.y=500;game.stage2Boss.vx=300;game.stage2Boss.vy=0;game.stage2Boss.setState('bolts-windup',1);const bossCoastX=game.stage2Boss.x;game.stage2Boss.update(.1,game);assert(game.stage2Boss.x>bossCoastX&&game.stage2Boss.vx<300,'boss windups must decelerate smoothly instead of freezing in place');game.stage2Boss.setState('bolts-windup',0);game.stage2Boss.update(.016,game);assert.equal(game.stage2Boss.state,'bolts-fire','Stage 2 boss must hold its casting pose when bolts launch');game.stage2Boss.stateTimer=0;game.stage2Boss.update(.016,game);assert.equal(game.stage2Boss.state,'recover');game.stage2Boss.setState('pulse-windup',0);game.stage2Boss.update(.016,game);assert.equal(game.stage2Boss.state,'pulse-fire','Stage 2 boss must hold its casting pose when the radial pulse launches');game.stage2Boss.stateTimer=0;game.stage2Boss.update(.016,game);assert.equal(game.stage2Boss.state,'recover');
game.stage2Boss.slamX=5500;game.stage2Boss.setState('slam-windup',0);game.stage2Boss.update(.016,game);assert.equal(game.stage2Boss.state,'slam-drop');game.stage2Boss.y=game.stage2Boss.arenaFloor-game.stage2Boss.h+2;game.stage2Boss.vy=200;game.stage2Boss.update(.016,game);assert.equal(game.stage2Boss.state,'slam-impact');assert(game.stage2Shockwaves.length>=2,'boss slam must emit ground shockwaves');assert(game.stage2BossEffects.at(-1).frame===3,'boss slam must create its generated impact eruption');drawImageCalls=[];game.stage2Shockwaves[0].draw(context2d);assert(drawImageCalls.some(args=>args[0]===SPRITES.stage2BossVfx&&args[1]===512&&args[2]===512),'loaded Stage 2 shockwave must draw generated frame 4');assert.equal(contextDepth,0,'Stage 2 shockwave drawing must balance canvas state');
game.stage2Boss.x=5600;game.stage2Boss.y=500;game.stage2Boss.vx=0;game.stage2Boss.vy=0;game.stage2Boss.dashTargetX=6100;game.stage2Boss.dashTargetY=500;game.stage2Boss.vfxTimer=.04;game.stage2Boss.setState('dash-windup',0);game.stage2Boss.update(.016,game);assert.equal(game.stage2Boss.state,'dash');assert.equal(game.stage2Boss.vfxTimer,0,'each Stage 2 dash must reset its trail timer');game.stage2Boss.update(.016,game);assert(game.stage2BossEffects.some(effect=>effect.frame===2),'Stage 2 dash must create generated afterimages immediately');
for(let i=0;i<50;i++)game.spawnStage2BossEffect(2,game.stage2Boss.cx,game.stage2Boss.cy,100,.3);assert(game.stage2BossEffects.length<=40,'boss VFX must stay capped during effect-heavy combat');const expiringEffect=game.stage2BossEffects.at(-1);expiringEffect.life=.001;game.updateStage2(.016);assert(!game.stage2BossEffects.includes(expiringEffect),'expired Stage 2 boss VFX must be removed');game.stage2BossEffects.length=0;
const bossStates=new Set();game.stage2Boss.x=5700;game.stage2Boss.y=520;game.stage2Boss.vx=0;game.stage2Boss.vy=0;game.stage2Boss.attack=0;game.stage2Boss.setState('recover',0);for(let i=0;i<1500;i++){game.stage2Boss.update(1/60,game);bossStates.add(game.stage2Boss.state);assert(Number.isFinite(game.stage2Boss.x)&&Number.isFinite(game.stage2Boss.y)&&Number.isFinite(game.stage2Boss.vx)&&Number.isFinite(game.stage2Boss.vy),'boss motion must stay finite');}for(const state of ['bolts-windup','dash-windup','slam-windup','slam-drop','slam-impact'])assert(bossStates.has(state),`boss combat loop must reach ${state} without stalling`);
game.stage2Projectiles.push({});game.stage2Shockwaves.push({});game.stage2Boss.kill(game);assert.equal(game.stage2Projectiles.length,0,'Stage 2 boss death must clear projectiles');assert.equal(game.stage2Shockwaves.length,0,'Stage 2 boss death must clear shockwaves');assert.equal(game.stage2BossEffects.length,1,'Stage 2 boss death must replace active effects with its finishing halo');assert.equal(game.stage2BossEffects[0].frame,5,'Stage 2 boss death must use the generated phase halo');drawImageCalls=[];game.stage2BossEffects[0].draw(context2d);assert(drawImageCalls.some(args=>args[0]===SPRITES.stage2BossVfx&&args[1]===1024&&args[2]===512),'loaded Stage 2 death halo must draw generated frame 5');assert.equal(contextDepth,0,'Stage 2 death halo drawing must balance canvas state');

// Stage 3: The Eclipse Foundry.
assert(/<button[^>]+id="stage3Mode"[\s\S]*?<h2>STAGE 3<\/h2>/i.test(html),'Stage 3 menu card must use the exact Stage 3 label');
for(const phrase of ['Eclipse Foundry','Solar Legionnaire','Flux Manta','Forge Weaver','Heliarch Zero'])assert(html.includes(phrase),`Stage 3 contract must mention ${phrase}`);
assert(html.includes('mastraVanguardStage3High'),'Stage 3 must use its own local best-score key');
const stage3SpriteContracts=[
  ['stage3-solar-legionnaire-frames-v2.png',4,2],['stage3-flux-manta-frames-v2.png',4,2],['stage3-forge-weaver-frames-v2.png',4,2],['stage3-heliarch-zero-frames-v2.png',4,2],['stage3-heliarch-vfx-frames-v2.png',3,2]
];
const stage3Bytes=[];
for(const [asset,columns,rows] of stage3SpriteContracts){const file=path.join(root,'assets','sprites',asset),png=fs.readFileSync(file);stage3Bytes.push(png);assert.equal(png[25],6,`${asset} must use RGBA PNG data`);const alpha=pngAlphaStats(png,columns,rows),pixels=alpha.width*alpha.height;assert.equal(alpha.width%columns,0,`${asset} width must divide into whole animation cells`);assert.equal(alpha.height%rows,0,`${asset} height must divide into whole animation cells`);assert(alpha.transparent>pixels*.2&&alpha.visible>pixels*.2,`${asset} must have real transparent and visible pixels`);for(const [frame,cell] of alpha.cells.entries()){assert(cell.transparent>1000&&cell.visible>1000,`${asset} frame ${frame} must contain transparent space and artwork`);assert.equal(cell.edge,0,`${asset} frame ${frame} must keep artwork inside its cell gutter`);}}
for(let i=0;i<stage3Bytes.length;i++)for(let j=i+1;j<stage3Bytes.length;j++)assert(!stage3Bytes[i].equals(stage3Bytes[j]),'Stage 3 sprite sheets must be distinct generated assets');
assert(fs.existsSync(path.join(root,'assets','backgrounds','stage3-eclipse-foundry-v1.png')),'Stage 3 background art must exist');assert(fs.existsSync(path.join(root,'assets','backgrounds','stage3-foundry-facades-v1.png')),'Stage 3 facade art must exist');
for(const [asset,width,height] of [['stage3-eclipse-foundry-v1.png',1774,887],['stage3-foundry-facades-v1.png',1536,1024]]){const png=fs.readFileSync(path.join(root,'assets','backgrounds',asset));assert.equal(png.readUInt32BE(16),width,`${asset} width must remain stable`);assert.equal(png.readUInt32BE(20),height,`${asset} height must remain stable`);assert.equal(png[25],2,`${asset} must be an opaque RGB environment texture`);}

game.startMode('stage3');game.audio.muted=true;assert.equal(game.isStage3,true,'Stage 3 selection must activate the Stage 3 mode');assert(game.stage3Hero instanceof Stage3Hero&&game.stage3Hero instanceof Player,'Stage 3 must use the shared Astra player system');assert.equal(game.stage3Platforms.length,16,'Stage 3 must initialize its authored platform layout');assert(game.stage3Enemies.some(enemy=>enemy instanceof SolarLegionnaire));assert(game.stage3Enemies.some(enemy=>enemy instanceof FluxManta));assert(game.stage3Enemies.some(enemy=>enemy instanceof ForgeWeaver));assert.equal(game.stage3Encounter,'clear-hostiles');
assert(game.stage3AggroDelay>=3.2,'Stage 3 must give the mission intro a fair non-attacking grace period');
for(const image of [SPRITES.stage3Map,SPRITES.stage3Facades,SPRITES.stage3Legionnaire,SPRITES.stage3Manta,SPRITES.stage3Weaver,SPRITES.stage3Boss,SPRITES.stage3BossVfx])markSpriteLoaded(image);
for(const facade of game.stage3Platforms.filter(platform=>platform.facade)){const supported=game.stage3Platforms.some(base=>!base.facade&&base.y===facade.y+facade.h&&base.x<=facade.x&&base.x+base.w>=facade.x+facade.w);assert(supported,`Stage 3 facade at ${facade.x} must sit on a continuous floor`);}
assert(game.stage3Platforms.some(platform=>platform.x<=STAGE3.arenaLeft&&platform.x+platform.w>=STAGE3.worldW&&platform.y===STAGE3.arenaFloor),'Stage 3 boss arena must have one continuous floor');
assert.equal(game.stage3SurfaceYAt(500,1560),1560,'hazards aimed at Astra on the street must not jump onto an overlapping facade rooftop');assert.equal(game.stage3SurfaceYAt(500,1200),1200,'hazards aimed at rooftop Astra must stay on that rooftop');

// Shared Astra parity: launch, heat vision, super beam, Nova, regen, and rendering.
game.stage3Hero.onGround=true;game.input.keys.add('shift');game.input.keys.add('w');for(let i=0;i<30;i++)game.stage3Hero.update(1/30,game);assert.equal(game.stage3Hero.flying,true,'Stage 3 must inherit the Power Launch flight burst');assert.equal(game.stage3Hero.speedBuild,1,'Stage 3 Power Launch must start at maximum boost build');assert.equal(game.stage3Hero.vx,0,'Stage 3 Power Launch must launch straight upward');assert.equal(game.stage3Hero.vy,-CFG.speedFlyMax,'Stage 3 Power Launch must use the maximum boosted flight speed');assert.equal(game.stage3LaunchWaves.length,1,'Stage 3 Power Launch must create one takeoff wave');game.input.clear();game.resetStage3();game.stage3LaunchWaves.length=0;const stage3LandingTarget=game.stage3Enemies[0];stage3LandingTarget.x=160;stage3LandingTarget.y=1484;const stage3LandingHp=stage3LandingTarget.hp;game.stage3Hero.flying=false;game.stage3Hero.onGround=false;game.stage3Hero.y=1493.5;game.stage3Hero.vy=machImpact;game.stage3Hero.speedBuild=CFG.sonicThreshold;game.stage3Hero.sonicBoomTriggered=true;game.stage3Hero.update(.016,game);assert(game.stage3Hero.onGround,'Stage 3 Mach descent must land on its floor');assert(game.stage3LaunchWaves.some(w=>w.impact),'Stage 3 Mach landing must create an impact shockwave');assert(stage3LandingTarget.hp<stage3LandingHp,'Stage 3 landing shockwave must damage a nearby enemy');game.stage3LaunchWaves.length=0;game.stage3Hero.onGround=false;game.stage3Hero.y=1493.5;game.stage3Hero.vy=machImpact;game.stage3Hero.speedBuild=0;game.stage3Hero.sonicBoomTriggered=false;game.stage3Hero.update(.016,game);assert(game.stage3Hero.onGround,'Stage 3 non-Mach fast descent must land on its floor');assert(!game.stage3LaunchWaves.some(w=>w.impact),'Stage 3 speed alone must not create a shockwave without Mach state');game.resetStage3();
const stage3Hero=game.stage3Hero;stage3Hero.hp=60;stage3Hero.healthRegenDelay=0;const hpBefore=stage3Hero.hp;stage3Hero.update(.25,game);assert(stage3Hero.hp>hpBefore,'shared Astra health regeneration must work in Stage 3');stage3Hero.onGround=true;stage3Hero.energy=CFG.maxEnergy;stage3Hero.flying=false;const stage3BeamTarget=game.stage3Enemies[0],stage3BeamOrigin=stage3Hero.beamOrigin(),stage3BeamHp=stage3BeamTarget.hp;stage3BeamTarget.x=stage3BeamOrigin.x+320;stage3BeamTarget.y=stage3BeamOrigin.y-stage3BeamTarget.h/2;game.input.mouse.x=stage3BeamTarget.x+stage3BeamTarget.w/2-game.camera.x;game.input.mouse.y=stage3BeamTarget.y+stage3BeamTarget.h/2-game.camera.y;game.input.mouse.down=true;stage3Hero.update(.016,game);assert(game.stage3HeatVision,'Stage 3 must use continuous heat vision');assert(Math.hypot(game.stage3HeatVision.ex-game.stage3HeatVision.x,game.stage3HeatVision.ey-game.stage3HeatVision.y)>=STAGE3.heatVisionRange*.99,'Stage 3 heat vision must span the full world range');assert(stage3BeamTarget.hp<stage3BeamHp,'Stage 3 heat vision must damage a visible enemy');game.input.mouse.down=false;game.input.clear();game.stage3Hero.fireSuperBeam(game,1);assert.equal(game.stage3Beams.length,1,'Stage 3 must inherit Super Beam');assert(Math.hypot(game.stage3Beams[0].ex-game.stage3Beams[0].x,game.stage3Beams[0].ey-game.stage3Beams[0].y)>=CFG.superBeamRange*.99,'Stage 3 Super Beam must span the full world range');const stage3Charges=stage3Hero.ultimateCharges;stage3Hero.castUltimate(game);assert.equal(stage3Hero.ultimateCharges,stage3Charges-1,'Stage 3 must inherit Prism Nova charges');assert(game.stage3Waves.length>0,'Stage 3 Prism Nova must create its shockwave');
stage3Hero.hp=65;stage3Hero.healthRegenDelay=0;stage3Hero.draw(context2d,game);assert.equal(contextDepth,0,'Stage 3 Astra rendering must balance canvas state');
game.resetStage3();const stage3FlightHero=game.stage3Hero;stage3FlightHero.onGround=true;game.input.pressed.add('f');stage3FlightHero.update(.016,game);assert.equal(stage3FlightHero.flying,true,'Stage 3 must retain Astra F flight toggle');drawImageCalls=[];stage3FlightHero.draw(context2d,game);assert(drawImageCalls.some(args=>args[0]===SPRITES.astraFlight),'Stage 3 F flight must use the shared sideways pose');game.input.clear();stage3FlightHero.flying=false;stage3FlightHero.onGround=true;stage3FlightHero.vx=CFG.runMax;stage3FlightHero.boosting=true;stage3FlightHero.updateLocomotion(.12);assert(stage3FlightHero.groundMotion>.7&&stage3FlightHero.sprintMotion>.7,'Stage 3 must retain shared walk and sprint blending');

// Hostiles animate before aggro and continue moving/attacking without freezing.
game.resetStage3();for(const image of [SPRITES.stage3Map,SPRITES.stage3Facades,SPRITES.stage3Legionnaire,SPRITES.stage3Manta,SPRITES.stage3Weaver,SPRITES.stage3Boss,SPRITES.stage3BossVfx])markSpriteLoaded(image);const openingLegionnaire=game.stage3Enemies.find(enemy=>enemy instanceof SolarLegionnaire),openingManta=game.stage3Enemies.find(enemy=>enemy instanceof FluxManta),openingWeaver=game.stage3Enemies.find(enemy=>enemy instanceof ForgeWeaver),openingLegionAnim=openingLegionnaire.anim,openingMantaX=openingManta.x,openingWeaverAnim=openingWeaver.anim,stage3OpeningHp=game.stage3Hero.hp;for(let i=0;i<150;i++)game.updateStage3(1/60);assert(openingLegionnaire.anim>openingLegionAnim&&openingManta.x!==openingMantaX&&openingWeaver.anim>openingWeaverAnim,'Stage 3 enemies must animate and move during the opening grace period');assert.equal(game.stage3Hero.hp,stage3OpeningHp,'Stage 3 opening grace period must not damage Astra');game.stage3AggroDelay=0;game.stage3Hero.invuln=999;const legX=openingLegionnaire.x;for(let i=0;i<260;i++)game.updateStage3(1/60);for(const enemy of game.stage3Enemies){assert(Number.isFinite(enemy.x)&&Number.isFinite(enemy.y)&&Number.isFinite(enemy.vx)&&Number.isFinite(enemy.vy),`${enemy.constructor.name} motion must stay finite`);assert(enemy.anim>0,`${enemy.constructor.name} animation must advance`);}assert(game.stage3Enemies.some(enemy=>enemy.x!==legX)||game.stage3Projectiles.length>0||game.stage3Hazards.length>0,'Stage 3 enemies must keep progressing into movement or attacks');
for(const enemy of game.stage3Enemies){const box=enemy.beamHitbox();assert(box.x<enemy.x+enemy.w&&box.x+box.w>enemy.x&&box.y<enemy.y+enemy.h&&box.y+box.h>enemy.y,`${enemy.constructor.name} beam hitbox must overlap its visible body`);}
game.resetStage3();game.stage3AggroDelay=0;game.stage3Hero.invuln=999;const farManta=game.stage3Enemies.filter(enemy=>enemy instanceof FluxManta)[1];farManta.attackCd=0;farManta.update(.5,game);assert.equal(farManta.state,'orbit','distant Flux Mantas must guard their sector instead of rushing the spawn');const manta=game.stage3Enemies.find(enemy=>enemy instanceof FluxManta);manta.x=game.stage3Hero.x+700;manta.y=game.stage3Hero.y-220;manta.attackCd=0;manta.state='orbit';manta.stateTimer=0;manta.update(.016,game);assert(['shot-windup','swoop-windup'].includes(manta.state),'a nearby Flux Manta must telegraph an attack');const farWeaver=game.stage3Enemies.filter(enemy=>enemy instanceof ForgeWeaver)[1];farWeaver.attackCd=0;farWeaver.update(.5,game);assert.equal(farWeaver.state,'idle','distant Forge Weavers must not attack Astra from across the map');const weaver=game.stage3Enemies.find(enemy=>enemy instanceof ForgeWeaver);weaver.x=game.stage3Hero.x+650;weaver.y=game.stage3Hero.y-280;weaver.attackCd=0;weaver.state='idle';weaver.stateTimer=0;weaver.update(.016,game);assert(['cast-windup','phase-out'].includes(weaver.state),'a nearby Forge Weaver must telegraph or phase before attacking');game.stage3Hero.x=3500;weaver.anchorIndex=0;weaver.relocate(game);assert(Math.abs(weaver.homeX-(game.stage3Hero.x+game.stage3Hero.w/2))<950,'Forge Weaver relocation must stay near Astra instead of forcing cross-map backtracking');
game.resetStage3();for(let i=0;i<420;i++)game.updateStage3(1/60);assert(!game.stage3Hero.dead&&game.stage3Hero.hp>40,'an idle Astra must not be spawn-killed before the Stage 3 introduction finishes');

// Complete boss flow, unique phases, attacks, cleanup, and victory.
game.stage3Enemies.length=0;game.stage3Hero.invuln=999;game.stage3Hero.x=STAGE3.arenaLeft-120;game.updateStage3(.016);assert.equal(game.stage3Encounter,'boss-ready','clearing Stage 3 hostiles must unlock the solar core');game.stage3Hero.x=STAGE3.arenaLeft+110;game.updateStage3(.016);assert.equal(game.stage3Encounter,'boss-intro');assert(game.stage3Boss instanceof HeliarchZero);assert(game.stage3BossEffects.some(effect=>effect.frame===5&&effect.followBoss),'Heliarch Zero intro must create a following phase halo');drawImageCalls=[];game.stage3Boss.draw(context2d);assert(drawImageCalls.some(args=>args[0]===SPRITES.stage3Boss),'Heliarch Zero must render its generated model sheet');assert.equal(contextDepth,0,'Heliarch Zero rendering must balance canvas state');for(let i=0;i<160;i++)game.updateStage3(1/60);assert.equal(game.stage3Encounter,'boss-fight','Stage 3 boss intro must resolve into combat');const heliarch=game.stage3Boss;heliarch.hp=heliarch.maxHp*.66;heliarch.update(.016,game);assert.equal(heliarch.phase,2,'Heliarch Zero must enter phase 2 at its health threshold');heliarch.hp=heliarch.maxHp*.33;heliarch.update(.016,game);assert.equal(heliarch.phase,3,'Heliarch Zero must enter phase 3 at its health threshold');
game.stage3Projectiles.length=0;heliarch.fireLances(game);assert(game.stage3Projectiles.length>=5,'Heliarch Zero must fire phase-scaled solar lances');game.stage3Hazards.length=0;heliarch.activateFoundry(game);assert(game.stage3Hazards.length>0,'Heliarch Zero must activate foundry hazards');game.stage3Sweeps.length=0;heliarch.startCoreSweep(game);assert.equal(game.stage3Sweeps.length,1,'Heliarch Zero must create a phase-three beam sweep');game.stage3Shockwaves.length=0;heliarch.slamImpact(game);assert.equal(game.stage3Shockwaves.length,2,'Heliarch Zero ground impact must emit two readable shockwaves');
heliarch.hp=heliarch.maxHp;heliarch.phase=1;heliarch.attack=0;heliarch.state='recover';heliarch.stateTimer=0;heliarch.stateDuration=0;heliarch.x=6320;heliarch.y=520;const stage3BossStates=new Set();for(let i=0;i<1700;i++){heliarch.update(1/60,game);stage3BossStates.add(heliarch.state);assert(Number.isFinite(heliarch.x)&&Number.isFinite(heliarch.y)&&Number.isFinite(heliarch.vx)&&Number.isFinite(heliarch.vy),'Heliarch Zero motion must stay finite');}for(const state of ['lance-windup','dash-windup','slam-windup','slam-drop'])assert(stage3BossStates.has(state),`Heliarch combat loop must reach ${state}`);
heliarch.hp=1;heliarch.hit(10,game);assert.equal(game.stage3Encounter,'boss-defeated');assert.equal(game.stage3Projectiles.length,0);assert.equal(game.stage3Shockwaves.length,0);assert.equal(game.stage3Hazards.length,0);for(let i=0;i<190;i++)game.updateStage3(1/60);assert.equal(game.victory,true,'Heliarch Zero defeat must complete Stage 3');assert.equal(game.victoryPlayed,true,'Stage 3 victory audio/bonus must trigger once');
game.restart();assert.equal(game.isStage3,true);assert.equal(game.stage3Encounter,'clear-hostiles');assert.equal(game.stage3Hero.dead,false);assert.equal(game.stage3Projectiles.length,0);assert.equal(game.input.keys.size,0);game.returnToMainMenu();assert.equal(game.started,false);assert.equal(game.stage3HeatVision,null);game.startMode('classic');assert.equal(game.isStage3,false);game.startMode('stage2');assert.equal(game.isStage2,true);game.startMode('stage3');assert.equal(game.isStage3,true,'stage transitions must be reversible');
storage.set('mastraVanguardStage3High','777');game.resetStage3();assert.equal(game.highScore,777,'Stage 3 best score must restore from its dedicated local-storage key');

assert(/id="godMode"[^>]*role="switch"/.test(html),'main menu God Mode control must be a toggle');assert(/id="pauseGodMode"[^>]*role="switch"/.test(html),'pause menu God Mode control must be a toggle');game.setGodMode(true);for(const mode of ['classic','stage2','stage3']){game.startMode(mode);assert(game.isGodMode,`God Mode toggle must persist into ${mode}`);assert.equal(game.activeHero.hp,CFG.maxHp,`${mode} God Mode must restore full health`);assert.equal(game.activeHero.energy,CFG.maxEnergy,`${mode} God Mode must restore full flight energy`);assert.equal(game.activeHero.speedEnergy,100,`${mode} God Mode must restore full speed energy`);assert.equal(elements.get('godMode').attributes.get('aria-pressed'),'true');assert.equal(elements.get('pauseGodMode').attributes.get('aria-pressed'),'true');}game.setGodMode(false);game.startMode('classic');assert(!game.isGodMode,'God Mode toggle must disable cleanly across stages');assert.equal(elements.get('godMode').attributes.get('aria-pressed'),'false');assert.equal(elements.get('pauseGodMode').attributes.get('aria-pressed'),'false');
assert.equal(game.activeHero.ultimateCharges,CFG.ultimateMaxCharges,'disabling God Mode must leave a valid Nova charge count');game.setGodMode(true);game.startMode('classic');game.player.ultimateCharges=0;game.player.ultimateCd=0;game.player.castUltimate(game);assert.equal(game.player.ultimateCharges,CFG.ultimateMaxCharges,'God Mode Nova must not consume charges');assert.equal(game.ultimateWaves.at(-1).radius,CFG.ultimateRadius,'Prism Nova must use the expanded 50% radius');game.player.ultimateCd=0;game.player.castUltimate(game);assert.equal(game.player.ultimateCharges,CFG.ultimateMaxCharges,'God Mode Nova must remain castable repeatedly');
for(const mode of ['stage2','stage3']){game.startMode(mode);const hero=game.activeHero;hero.ultimateCharges=0;hero.ultimateCd=0;hero.castUltimate(game);assert.equal(hero.ultimateCharges,CFG.ultimateMaxCharges,`${mode} God Mode Nova must not consume charges`);}

game.mode='classic';game.reset();assert(game.player instanceof Player);assert.equal(game.encounterState,'clear-hostiles');

// Production audit regressions: deterministic timing, shared systems, loading and accessibility.
assert.equal(Stage2Hero.prototype.update,Player.prototype.update,'Stage 2 must not maintain a duplicate movement implementation');
assert.equal(Stage2Hero.prototype.castUltimate,Player.prototype.castUltimate,'Nova must be shared across every stage');
assert.equal(SIM_STEP,1/120,'simulation should run at 120 Hz independently of rendering');
for(const mode of ['classic','stage2','stage3']){
  for(const scenario of ['run','flight','boost']){
    const outcomes=[];
    for(const fps of [30,60,120,144]){
      game.setGodMode(false);game.startMode(mode);game.audio.muted=true;game.activeEnemies.length=0;
      const hero=game.activeHero;
      if(scenario!=='run'){hero.x=1500;hero.y=500;hero.flying=true;}
      game.input.keys.add('d');if(scenario==='boost')game.input.keys.add('shift');
      for(let frame=0;frame<fps*2;frame++)game.advanceFrame(1/fps);
      outcomes.push([hero.x,hero.y,hero.vx,hero.vy,hero.energy,hero.speedEnergy,hero.speedBuild,game.runStats.time]);
    }
    for(const outcome of outcomes)outcome.forEach((value,i)=>assert(Math.abs(value-outcomes[0][i])<1e-7,`${mode} ${scenario}: 30/60/120/144 Hz must produce the same gameplay state`));
  }
  game.startMode(mode);game.activeEnemies.length=0;const hero=game.activeHero;
  hero.flying=true;hero.x=1500;hero.y=500;hero.vx=CFG.speedFlyMax;hero.speedBuild=1;game.input.keys.add('d');
  hero.update(SIM_STEP,game);assert(hero.vx>CFG.speedFlyMax*.95,`${mode}: releasing Shift must decelerate instead of snapping to normal flight speed`);
  hero.speedEnergy=.01;game.input.keys.add('shift');hero.update(SIM_STEP,game);assert(hero.speedExhausted);
  hero.update(SIM_STEP,game);assert(!hero.boosting,'depleted boost must not flutter on/off each tick');
  game.input.clear();game.restart();hero.dead=false;
  const current=game.activeHero;current.onGround=true;current.speedEnergy=0;game.input.keys.add('shift');game.input.keys.add('w');
  assert(!current.beginPowerLaunch(game),'Power Launch must respect speed energy as well as flight energy');
  game.input.clear();game.setGodMode(true);current.y=game.worldConfig.worldH+100;current.invuln=0;current.update(SIM_STEP,game);
  assert.equal(current.y,current.spawnY,`${mode}: God Mode must recover from the void`);
  game.setGodMode(false);game.restart();current.ultimateCd=0;
  game.activeHero.ultimateCharges=0;game.activeHero.castUltimate(game);assert.equal(game.activeHero.ultimateCharges,0,'direct Nova calls cannot create negative charges');
}
game.startMode('classic');game.activeEnemies.length=0;game.input.pressed.add('f');game.advanceFrame(.001);
assert(game.input.hit('f'),'inputs must survive render frames without a simulation step');game.advanceFrame(SIM_STEP);
assert(game.player.flying,'buffered F must execute on the next simulation step');
const elapsedBeforePause=game.runStats.time;game.setPaused(true);game.advanceFrame(1);
assert.equal(game.runStats.time,elapsedBeforePause,'pauses must not count toward mission time');
game.setPaused(false);assert(game.advanceFrame(5)<=12,'long stalls must have a bounded catch-up budget');
game.player.onGround=true;game.player.flying=false;game.player.launchCharging=true;game.player.chargingBeam=true;
game.setPaused(true);assert(!game.player.launchCharging&&!game.player.chargingBeam,'pause must cancel charge states and clear continuous attacks');
game.restart();

// Interpolation is presentation-only and never leaks altered coordinates into collision.
const renderedBody={x:24,y:32,simX:16,simY:24};interpolateRenderBody(renderedBody,.5);
assert.equal(renderedBody.x,20);restoreRenderBody(renderedBody);assert.equal(renderedBody.x,24);
const teleportedBody={x:900,y:20,simX:0,simY:0};interpolateRenderBody(teleportedBody,.5);assert.equal(teleportedBody.x,900);restoreRenderBody(teleportedBody);

// Piercing beam damage and enemy response must not depend on hit-call frequency.
for(const fps of [30,60,120,144]){
  game.setGodMode(false);game.startMode('classic');const target=game.enemies[0];target.hp=10000;target.maxHp=10000;
  const vx=target.vx;let feedback=0;const burst=game.burst;game.burst=()=>feedback++;
  for(let i=0;i<fps;i++){target.hit(CFG.heatVisionDamage/fps,game);target.hitFeedbackCd=Math.max(0,(target.hitFeedbackCd||0)-1/fps);}
  game.burst=burst;assert(Math.abs(target.hp-(10000-CFG.heatVisionDamage))<1e-7);assert.equal(target.vx,vx,'beam hits must not repeatedly multiply enemy velocity');assert(feedback<=7,'impact FX should be rate-limited');
}
game.startMode('classic');game.setGodMode(true);const godTarget=game.enemies[0];godTarget.hp=10000;
game.player.x=100;game.player.y=1200;game.player.aimAngle=0;const origin=game.player.beamOrigin();godTarget.x=origin.x+220;godTarget.y=origin.y-godTarget.h/2;
game.input.mouse.x=godTarget.x-game.camera.x;game.input.mouse.y=origin.y-game.camera.y;game.player.fireHeatVision(.1,game);
assert(Math.abs(godTarget.hp-(10000-CFG.heatVisionDamage*.1*5))<.001,'God Mode multiplier must apply to continuous beam DPS');
game.setGodMode(false);game.restart();const boomTarget=game.enemies[0];boomTarget.x=game.player.x+90;boomTarget.y=game.player.y;boomTarget.telegraph=.4;
const boomHp=boomTarget.hp;assert(game.triggerSonicBoom(game.player));assert.equal(boomTarget.hp,boomHp-28);assert(boomTarget.staggerTimer>0);assert.equal(boomTarget.telegraph,0,'Sonic Boom should interrupt a minion windup');
assert.equal(game.triggerSonicBoom(game.player),false,'Mach-threshold spam cannot repeat the combat pulse');assert.equal(boomTarget.hp,boomHp-28);

// High-speed projectiles must hit when they cross Astra between two simulation samples.
game.restart();game.player.x=500;game.player.y=400;game.player.previousX=500;game.player.previousY=400;
const fastShot=new HostileProjectile(400,430,12000,0);fastShot.update(.02,game);
assert(fastShot.dead&&game.player.hp<100,'swept projectile collision must prevent tunneling');
game.restart();game.particlePool.length=0;const pooled=new Particle(0,0,0,0,.001,'#fff');game.particles=[pooled];game.updateParticles(.1);
assert(game.particlePool.includes(pooled));game.addParticle(0,0,0,0,.5,'#abc');assert.equal(game.particles.at(-1),pooled,'expired particles must be reused');
game.settings.quality='low';game.particles.length=0;game.burst(0,0,'#fff',10000);assert(game.particles.length<=230);
game.settings.reducedMotion=true;game.particles.length=0;game.burst(0,0,'#fff',10000);assert(game.particles.length<=140);
game.settings.shake=0;game.shake=100;assert.equal(game.visibleShake,0);
game.settings.quality='high';game.settings.reducedMotion=false;game.settings.reducedFlashing=true;game.settings.save();
const persistedDisplay=new DisplaySettings();assert.equal(persistedDisplay.shake,0);assert(persistedDisplay.reducedFlashing);
markSpriteLoaded(SPRITES.astraIdle);game.player.onGround=true;game.player.invuln=.8;drawImageCalls=[];game.player.draw(context2d,game);assert(drawImageCalls.length>0,'reduced flashing must keep Astra visible during invulnerability');
game.settings.reducedFlashing=false;

// Stage-specific asset sets must include boss artwork without loading another planet.
for(const [mode,prefix] of [['classic','warden'],['stage2','stage2Boss'],['stage3','stage3Boss']]){
  const assets=stageAssets(mode);assert(assets.includes(SPRITES.astraFlight));assert(assets.includes(mode==='classic'?SPRITES.wardenIdle:SPRITES[prefix]));
  if(mode!=='stage2')assert(!assets.includes(SPRITES.stage2Map));
  if(mode!=='stage3')assert(!assets.includes(SPRITES.stage3Map));
}
const loadSuccess=new MockImage();loadSuccess.pendingSrc='success.png';loadSuccess.decode=()=>Promise.resolve();
const readySuccess=readySprite(loadSuccess);markSpriteLoaded(loadSuccess);loadSuccess.listeners.get('load')();assert.equal(await readySuccess,true);
const loadFailure=new MockImage();loadFailure.pendingSrc='missing.png';const readyFailure=readySprite(loadFailure);loadFailure.listeners.get('error')();assert.equal(await readyFailure,false,'failed artwork must resolve to fallback, not hang stage loading');

// Sweep telegraph has no active damage; its live ray uses the same visible beam width.
game.startMode('stage3');game.stage3Boss=new HeliarchZero(6000,800);game.stage3Encounter='boss-fight';
const sweep=new HeliarchSweep(game.stage3Boss,0);game.stage3Hero.x=game.stage3Boss.cx+100;game.stage3Hero.y=game.stage3Boss.cy-20;
const sweepHp=game.stage3Hero.hp;sweep.update(.1,game);assert.equal(game.stage3Hero.hp,sweepHp,'sweep warning must be harmless');
sweep.life=sweep.active/2;sweep.update(0,game);assert(game.stage3Hero.hp<sweepHp,'active sweep must hit visible overlapping targets');
assert(html.includes('angle=warning?this.startAngle'),'sweep warning must point toward the first active angle');

// All three genuine boss-death paths show results once, preserve score, and restart cleanly.
for(const mode of ['classic','stage2','stage3']){
  game.setGodMode(false);game.startMode(mode);game.activeHero.invuln=999;game.activeEnemies.length=0;
  game.activeHero.x=mode==='classic'?4200:mode==='stage2'?5300:5900;game.update(SIM_STEP);
  assert.equal(game.activeEncounter,'boss-intro');
  for(let i=0;i<360;i++)game.advanceFrame(SIM_STEP);
  assert.equal(game.activeEncounter,'boss-fight');game.activeBoss.kill(game);
  for(let i=0;i<360&&!game.victory;i++)game.advanceFrame(SIM_STEP);
  assert(game.victory&&game.results,`${mode}: boss death must produce a completion result`);
  const result=game.results,score=game.score;game.advanceFrame(1);assert.equal(game.results,result);assert.equal(game.score,score,'completion bonus must only be awarded once');
  assert.equal(elements.get('resultsMenu').attributes.get('aria-hidden'),'false');
  for(let i=0;i<8;i++){game.restart();assert.equal(game.activeEncounter,'clear-hostiles');assert.equal(game.results,null);assert.equal(game.runStats.time,0);assert(game.particlePool.length<=520);}
  const normalKey=game.highScoreKey;game.setGodMode(true);assert.notEqual(game.highScoreKey,normalKey,'God runs must use a separate best score in every stage');
  game.setGodMode(false);assert.notEqual(game.highScoreKey,normalKey,'turning God Mode off cannot reclassify an assisted run');
  game.restart();assert.equal(game.highScoreKey,normalKey,'a fresh normal run restores its unassisted score category');
}
assert.equal(contextDepth,0,'all regression drawing must restore Canvas state');
console.log('Mastra Vanguard smoke tests: PASS (including 30/60/120/144 Hz, all-stage results, loading, pooling and accessibility)');
